playbooks/base-minimal-test/post-logs.yaml, playbooks/base-minimal-test/post-ssh.yaml, playbooks/base-minimal-test/pre.yaml, playbooks/base-minimal/post-logs.yaml, playbooks/base-minimal/post-ssh.yaml, playbooks/base-minimal/pre.yaml, zuul.d/jobs.yaml
This is our first commit to start testing zuul.ansible.com. This is
lacking any sort of log publishing, and mostly to start validating our
nodepool integration.
Because we are not gating yet, we'll also be force merging these changes
until we have everything in place.
=> Initial commit of base-minimal / base-minimal-test jobs

zuul.d/pipelines.yaml
All projects will first need to pass the check pipeline, eventually
entering the gate pipeline. For now only add check so we can do some
initial testing.
=> Create check pipeline

zuul.d/pipelines.yaml
Update zuul pipeline configuration with gate info and ansible-zuul
github app.
=> Create gate pipeline

README.rst
We'll be building sphinx integration around it.
=> Switch to rst for README

playbooks/base-minimal/post-logs.yaml, playbooks/base-minimal/pre.yaml, zuul.d/jobs.yaml
I've confirmed log publishing works for swift!
=> Promote base-minimal-test changes

zuul.d/jobs.yaml
This works as expected, remove ubuntu-bionic for now.
=> Promote base-minimal-test (centos-7-1vcpu)

zuul.d/projects.yaml
Now that everything is green, gate our configuration.
=> Gate tox-linters job

zuul.d/pipelines.yaml
This migrates over the rest of our pipelines we use for jobs.
=> Add more pipelines

zuul.d/pipelines.yaml
We'll mostly use this to CD zuul.ansible.com from merged PRs.
=> Add promote pipeline

zuul.d/projects.yaml
This is to confirm our github application is setup properly, once
working we can properly gate this repo.
=> Add noop job to windmill

zuul.d/projects.yaml
This adds jobs to our new project in zuul.
=> Add ansible-python-jobs for ansible-network/arista_eos

tools/zuul-projects-checks.py, tox.ini, zuul.d/projects.yaml
We'll use this to help keep our zuul.d/projects.yaml file in order.
=> Add tools/zuul-projects-checks.py

zuul.d/projects.yaml
=> Add noop-jobs for ansible-network/sandbox

zuul.d/projects.yaml
We'd like to start gating on this project.
=> Add ansible-network/resource_module_builder to zuul ansible tenant

zuul.d/projects.yaml
We'll also be adding this all projects we gate for github.com/ansible.
=> Add system-required to all github.com/ansible-network projects

zuul/tenants.yaml
We plan to gate this repo with zuul.
=> Add ansible-network/cisco_nxos to ansible zuul tenant

README.rst
=> Update README about zuul tenant config files

README.rst
=> Add more documentation about this repo

zuul/tenants.yaml
=> Add extra docs to zuul/tenants.yaml

zuul/tenants.yaml
=> Documentation update for zuul/tenants.yaml

zuul.d/projects.yaml
=> Add jobs to ansible-network/cisco_nxos

zuul/tenants.yaml
We want to start running gate jobs on this project.
=> Add ansible-network/cisco_iosxr to ansible zuul tenant

zuul.d/projects.yaml
=> Add gate jobs to ansible-network/cisco_iosxr

zuul/tenants.yaml
We'd like to start gating this project.
=> Add ansible-network/releases to ansible zuul tenant

zuul/tenants.yaml
We'll be gating this project with zuul.
=> Add ansible-network/aws to zuul ansible tenant

zuul/tenants.yaml
=> Add ansible-network/config_manager to ansible zuul tenant

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/config_manager

zuul/tenants.yaml
We want to gate commit on this project.
=> Add ansible-network/resource_module_models to zuul

zuul/tenants.yaml
Another project we plan on gating with zuul.
=> Add ansible-network/resource_module_planning project to zuul

zuul.d/projects.yaml
=> Add noop jobs to ansible-network/resource_module_models

zuul.d/projects.yaml
=> Add noop-jobs for ansible-network/resource_module_planning

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/network-runner

zuul/tenants.yaml
We'd like to start gating this project.
=> Add ansible-network/frr to ansible zuul tenant

zuul.d/projects.yaml
=> Add noop-jobs for ansible-network/frr

zuul/tenants.yaml
We want to gate commit on this project.
=> Add ansible-network/configure-system-properties to zuul

zuul/tenants.yaml
We'll be gating this project with zuul.
=> Add ansible-network/network-image-builder to zuul

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/configure-system-properties

zuul.d/projects.yaml
=> Add noop-jobs for ansible-network/network-image-builder

zuul/tenants.yaml
We'll want to gate this repo with zuul.
=> Add ansible-network/rhel to ansible zuul tenant

zuul/tenants.yaml
=> Add 3 network provider roles

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/azure

zuul.d/projects.yaml
=> Add noop-jobs for ansible-network/openstack

zuul.d/projects.yaml
=> Add noop-jobs for ansible-network/rhel

zuul.d/projects.yaml
=> Add noop-jobs for ansible-network/cisco_asa

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/linux_network

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/network_configurator

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/net_operations

zuul/tenants.yaml
We'll be gating these repos with zuul.
=> Add ansible-network cloud_vpn roles to zuul

zuul.d/projects.yaml
=> Add noop-jobs to cloud_vpn roles

zuul/tenants.yaml
=> Add ansible-network/backup_config to ansible zuul tenant

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/backup_config

zuul/tenants.yaml
=> Add ansible-network/network-proposals to zuul ansible tenant

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/network-proposals

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/configure-vlan

zuul.d/projects.yaml
=> Add noop-jobs to ansible-network/content_store

playbooks/base-minimal-test/post-logs.yaml, roles/ara-report-fork/README.rst, roles/ara-report-fork/defaults/main.yaml, roles/ara-report-fork/tasks/main.yaml
This is to validate our fix propelry works.
=> base-test: used forked version of ara-report

zuul.d/projects.yaml
We've retired the following projects, as such we can now remove them
from zuul.
=> Retire some projects

test-requirements.txt, tools/zuul-projects-checks.py, tox.ini
We should be running lint checks on our python files too.
=> Add flake8 to tox -elinters

github/projects.yaml, tools/manage-projects.py
We are not able to archived a project, however once archived there is no
API to unarchived it. This will require us to land the projects.yaml
changes, removing archived flag, then a human to remove it via github
web interface.
=> Add the ability to archive projects

zuul.d/jobs.yaml, zuul.d/projects.yaml
We want to run lint check on our github/projects.yaml file.
=> Add project-config-tox-github job

github/projects.yaml
Start to import our existing projects to our yaml file.
=> Add ansible-network/content_store to github/projects.yaml

zuul.d/projects.yaml
This allows us to promote changes each time we update
github/projects.yaml.
=> Run project-config-github-promote promote job

github/projects.yaml
This is mostly to confirm our promote job works properly.
=> Update ansible-network/content_store description on github

zuul.d/projects.yaml
This job is passing properly, lets make it voting.
=> Make ansible-tox-py27 voting for ansible/ansible-runner

github/projects.yaml
=> Import more projects into github/projects.yaml

github/projects.yaml
This allows us to manage the repo with our automation.
=> Add ansible/network to github/projects.yaml

zuul.d/jobs.yaml
We only need to run this job when specific files change.
=> Add files filter to project-config-tox-github

zuul/tenants.yaml
We'll be starting to gate this repo with zuul.
=> Add ansible/network to ansible zuul tenant

zuul.d/projects.yaml
=> Add gating jobs to github.com/ansible/network

zuul/tenants.yaml
We are now gating this repo, it is safe to load configuration from it.
=> Load jobs from ansible/ansible-runner

zuul.d/projects.yaml
=> Add system-required to ansible/ansible-zuul-jobs

zuul.d/projects.yaml
=> Add python jobs to ansible-network/vyos

zuul.d/projects.yaml
We'll be gating on these projects.
=> Add jobs to ansible-network/yang

github/projects.yaml, zuul/tenants.yaml
Start doing gitops on ansible-network/cisco_ios for github and start to
gate it with zuul.
=> Import ansible-network/cisco_ios project

zuul.d/projects.yaml
We are ready to gate this repo with zuul.
=> Add python jobs to ansible-network/cisco_ios

github/projects.yaml
=> Fix syntax error with github/projects.yaml

zuul.d/projects.yaml
=> Add python jobs to ansible-network/network-engine

github/projects.yaml
Add this project to github/projects.yaml so we can automate the
management of it.
=> Manage ansible-network/cloud_vpn via automation

zuul.d/projects.yaml
Add jobs so we can start gating.
=> Add linter jobs to ansible-network/cloud_vpn

github/projects.yaml
Manage a few more projects via automation.
=> Add projects to github/projects.yaml

zuul/tenants.yaml
We want to be able to do cross-project testing with ansible/ansible.
=> Add ansible/ansible to ansible zuul tenant

github/projects.yaml
This is the first step to onboarding ansible-bender to zuul.ansible.com.
=> Manage ansible-community/ansible-bender github setting

zuul.d/projects.yaml
=> Add default-branch to ansible/awx

zuul.d/projects.yaml
Reverts ansible/project-config#138
=> Revert "adding python 2.7 unit tests to network-runner"

zuul.d/projects.yaml
=> Set default-branch for ansible/ansible

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/42
=> Test ansible-test-network-integration-vyos periodic jobs

zuul.d/projects.yaml
Now that these are working as expected, only run them daily.
=> Promote ansible-test-network-integration-vos to periodic

zuul.d/projects.yaml
Test these jobs work under periodic pipelines.
=> Add ansible-test-network-integration-eos to periodic-1hr

zuul.d/projects.yaml
=> Fix typo with previous commit

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/60
=> Switch to project-template for ansible/anible

zuul.d/pipelines.yaml
=> Add status URL for third-party-check pipeline

playbooks/base-minimal-test/post-logs.yaml, playbooks/base-minimal-test/pre.yaml
=> Don't gather_facts on localhost

zuul.d/jobs.yaml
This reverts commit 6b837f6606582f72635e43cc9710f5b362d9616c.
=> Revert "Set ara_report_executable for ara-report role"

zuul.d/projects.yaml
This starts the process of gating bender with zuul.
=> Add noop-jobs to ansible-community/bender

playbooks/base-minimal-test/pre.yaml, roles/prepare-workspace-fork/README.rst, roles/prepare-workspace-fork/defaults/main.yaml, roles/prepare-workspace-fork/tasks/main.yaml
=> Add prepare-workspace-fork to debug ze02 failures

github/projects.yaml, zuul/tenants.yaml
With the new work we are doing with ansible collections, create one for
VyOS so we can start testing.
=> Add ansible_collections.vyos.vyos to ansible zuul tenant

zuul.d/projects.yaml
This is to start the gating process.
=> Add noop-jobs to ansible-network/ansible_collections.vyos.vyos

zuul.d/pipelines.yaml
It is helpful to add the ability to run adhoc jobs in some cases, this
pipeline is for that purpose.
=> Add experimental pipeline

zuul.d/pipelines.yaml
=> Simplify 'check experimental' regex

github/projects.yaml, zuul/tenants.yaml
This is our new arista eos collection we'll be testing.
=> Add ansible-network/ansible_collections.arista.eos to zuul

github/projects.yaml
=> Better descriptions for ansible network collections

zuul.d/projects.yaml
=> Add noop jobs to arista.eos collection

github/projects.yaml, zuul/tenants.yaml
This will be our next colleciton we are tetsing for ansible network.
=> Add ansible-network/ansible_collections.cisco.ios to zuul

zuul.d/projects.yaml
This starts the gating process.
=> Add noop jobs to cisco ios collection

github/projects.yaml, zuul/tenants.yaml
This is our next collection we plan on testing with zuul.
=> Add ansible-network/ansible_collections.juniper.junos to zuul

zuul.d/projects.yaml
=> Add noop jobs to ansible_collections.juniper.junos

github/projects.yaml, zuul/tenants.yaml
=> Add iosxr collection to zuul

zuul.d/projects.yaml
This starts gating the iosxr collection with zuul.
=> Add noop jobs for iosxr collection

zuul.d/projects.yaml
=> Add gate jobs to network.cli collection

zuul/tenants.yaml
We want to do some POC testing for collections.
=> Add ansible/ansible-bare to ansible tenant

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/182
=> Start gating integration jobs on vyos.vyos collection

zuul.d/projects.yaml
This starts the gating process.
=> Add noop jobs for ansible-network/network_content_collector

playbooks/propose-github-updates/post.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
We'll use this job, if we need to interact with creating PRs on
github.com.
=> Create propose-github-updates job

playbooks/propose-github-updates/pre.yaml, zuul.d/jobs.yaml
This adds the proper usename / email address for the account.
=> Setup git.config for propose-github-updates job

playbooks/propose-github-updates/post.yaml
=> Fix syntax issue with post-run playbook

playbooks/propose-github-updates/post.yaml
Otherwise, we'll try to use vim, which doesn't work with our automation.
=> Use cat to create commit messages

playbooks/propose-github-updates/post.yaml
=> Only run git-pull-request for jobs that are successful

github/projects.yaml, zuul/tenants.yaml
=> Add ansible-network/ansible_collections.network.netconf to zuul

zuul.d/projects.yaml
=> Add jobs to network.netconf collection

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/189
=> Add junos-netconf integration jobs to netconf collection

playbooks/base-minimal-test/post-logs.yaml
=> Add retry handler to swift upload logs role

zuul.d/projects.yaml
=> Add ansible-collections-cisco-iosxr-netconf to network.netconf

playbooks/base-minimal-test/post-logs.yaml, zuul.d/secrets.yaml
=> No log on upload-logs-swift

playbooks/base-minimal-test/post-logs.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
Rackspace has more regions for swift, lets also test uploads there.
=> Add more regions for rackspace swift

playbooks/base-minimal-test/post-logs.yaml
=> Add back vexxhost for primary log location

zuul.d/pipelines.yaml
We want to use to try and sync our collections faster then once a day.
=> Add periodic-6hr pipeline

zuul.d/projects.yaml
=> Add linting jobs to cisco.nxos collection

zuul/tenants.yaml
Want to experiment with the metal3 project and zuul.
=> Add metal3-io/metal3-dev-env project for testing

zuul/tenants.yaml
We'll use this repo to test our new github app for 3pci testing only.
=> Add pabelanger/pabelanger-sandbox1 to zuul

zuul.d/pipelines.yaml
This is to validate our new github app works as expected.
=> Add example 3pci-check

zuul.d/projects.yaml
=> Add noop jobs to pabelanger/pabelanger-sandbox1

github/projects.yaml, zuul/tenants.yaml
Lets start to gate this project with zuul!
=> Add ansible-security/ids_config to zuul ansible tenant

zuul.d/projects.yaml
=> Add noop-jobs to ansible-security/ids_config

github/projects.yaml, zuul.d/projects.yaml, zuul/tenants.yaml
Signed-off-by: Adam Miller <admiller@redhat.com>
=> add ids_install from ansible-security

zuul.d/projects.yaml
Signed-off-by: Adam Miller <admiller@redhat.com>
=> add ansible-security/ids_install to projects

.yamllint
This commit fixes a new minor linting error with yamllint
=> Fix new linting error with yamllint

zuul.d/secrets.yaml
This will be used to interact with https://galaxy-dev.ansible.com,
something we'll use when we start publishing collections.
=> Add galaxy_dev_secret secret

playbooks/ansible-collection/pre.yaml, playbooks/ansible-collection/run.yaml, zuul.d/jobs.yaml
This is going to be the first of a few commits to try and get collection
publish jobs working. For now, we are just going to setup ansible-galaxy
to ensure we can build the collections.
=> First attempt at release-ansible-galaxy-collection job

playbooks/ansible-collection/run.yaml, zuul.d/jobs.yaml
Move to the next step of testing.
=> Build ansible-collection in release job

playbooks/ansible-collection/run.yaml
=> Fix typo with ansible-collections release job

playbooks/ansible-collection/post.yaml
=> Display stats on collections tarballs

zuul.d/projects.yaml
=> Add linters jobs to ansible-network/releases

playbooks/ansible-collection/run-pre.yaml
=> Fix typo in previous commit

playbooks/publish/ansible-galaxy.yaml, zuul.d/jobs.yaml
Now that we know we can properly build an ansible collection, next step
is to publish the content to galaxy.
=> Attempt to publish ansible-galaxy collections

playbooks/publish/ansible-galaxy.yaml
=> Fix typo with publish/ansible-galaxy.yaml

zuul.d/jobs.yaml
=> Set release-ansible-collection jobs to use ansible 2.9

zuul.d/jobs.yaml
We'll use this job to publish collections to galaxy-dev.
=> Add release-ansible-collection-galaxy-dev job

zuul.d/jobs.yaml, zuul.d/secrets.yaml
We are now ready to try and publish a collection to galaxy.a.c.
=> Finalize release-ansible-collection-galaxy job

zuul.d/projects.yaml
Now that we know our release jobs work, lets do all other collections.
=> Publish all network collections to galaxy

zuul.d/projects.yaml
=> Add noop jobs to ansible-network/network_collections_migration

zuul/tenants.yaml
We won't gate jobs on this project, but it will be helpful to use
depends-on with this repo.
=> Add ansible-community/collection_migration to zuul

github/projects.yaml, zuul/tenants.yaml
This is our new collection which will contain shared network code for
collections.
=> Add ansible-network/community.netcommon

zuul.d/projects.yaml
This is our basic set of jobs we want to start running on the repo.
=> Add jobs to ansible-network/community.netcommon

zuul.d/jobs.yaml
Projects can use this job to confirm collection builds work properly.
=> Create build-ansible-collection-galaxy job

zuul.d/jobs.yaml
We want people outside of project-config to run this.
=> Remove abstract on build-ansible-collection job

playbooks/ansible-collection/post.yaml
This splits out the artifact into name and version number.
=> Add more info into collection artifact

playbooks/ansible-collection/post.yaml
=> Fix syntax errors

playbooks/build-ansible-collections/post.yaml, playbooks/build-ansible-collections/pre.yaml, playbooks/build-ansible-collections/run.yaml, zuul.d/jobs.yaml
This now support building multiple collections and returning them to
zuul.
=> Add new build-ansible-collections job

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/workshops/pull/602
=> ansible/workshops: Make zuul vote as third party CI

zuul.d/projects.yaml
=> Add default branch for ansible-collection-migration/ansible-minimal

zuul.d/projects.yaml
Add needed jobs to build collections.
=> Add jobs for ansible_collections.ansible.netcommon

zuul.d/projects.yaml
We'll want to gate commits together to avoid breaking each other.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/275
=> Add network collections into integrated queue

zuul.d/projects.yaml, zuul/tenants.yaml
This POC is done, and no longer needed.
=> Remove github.com/pabelanger/pabelanger-sandbox1

zuul.d/projects.yaml
=> Add system-required to ansible-security projects

zuul.d/projects.yaml
All projects we gate, will need this template.
=> Add system-required project-template to molecule projects

zuul.d/projects.yaml
Lets start to run jobs on this repo.
=> Add ansible-collections-cisco-iosxr-netconf to ansible.netcommon

zuul.d/projects.yaml
These are no longer going to be used, so prepare to retire them.
=> Prepare to retire obsolete collection repos

github/projects.yaml, zuul/tenants.yaml
This will be our new junos collection, we plan to retire the existing.
=> Add ansible-network/ansible_collections.junipernetworks.junos to zuul

zuul.d/projects.yaml
=> Add jobs to junipernetworks.junos collection

zuul.d/projects.yaml
We are now ready to begin testing.
=> Add ansible-collections-juniper-junos-netconf to ansible.netcommon

zuul/tenants.yaml
We want to start doing cross project testing on network jobs.
=> Add ansible/pylibssh to ansible tenant

zuul.d/projects.yaml
We no longer plan to run tests on this project.
=> Prepare to retire ansible-network/ansible_collections.juniper.junos

zuul.d/projects.yaml
=> Prepare to retire ansible-network/network_content_collector

zuul.d/projects.yaml
All projects that gate, need to include these project-templates.
=> Add system-required to molecule community projects

zuul.d/projects.yaml
=> Add system-required to ansible-community/molecule

playbooks/publish/pypi.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
Projects will be able to opt into this job, to release python projects
to pypi.
=> Add release-ansible-python job

playbooks/build-python-tarball/post.yaml, playbooks/build-python-tarball/pre.yaml, playbooks/build-python-tarball/run.yaml, zuul.d/jobs.yaml
Fix issue found with testing the new job.
=> Update release-ansible-python job

playbooks/publish/pypi.yaml, zuul.d/secrets.yaml
=> Update testpypi_secret info for testpypi

playbooks/publish/pypi.yaml, zuul.d/jobs.yaml
=> Set release-ansible-python job to centos-8

playbooks/publish/pypi.yaml
=> Fix typo in pypi publish job

github/projects.yaml, zuul/tenants.yaml
Reverts ansible/project-config#324
This didn't promote properly, revert to unblock running windmill-config
=> Revert "add virt-lightning/esxi-cloud-images in Zuul"

github/projects.yaml, zuul/tenants.yaml
We'll import this collection into ansible-network for testing, then
we'll find the properly location for it.
=> Add ansible-network/ansible_collections.community.vmware to zuul

github/projects.yaml, zuul/tenants.yaml
This both creates the new repos and adds initial configuration to zuul.
=> Create network collections for ansible-collections

github/projects.yaml, zuul/tenants.yaml
Add the following repositories:
- ansible-collections/vmware
- ansible-collections/vmware_rest
- ansible-collections/amazon
=> add Ansible team repositories

github/projects.yaml, zuul/tenants.yaml
Creating Cisco ASA collection in the github projects and zuul
=> For creating Cisco ASA collection in the github projects and zuul

zuul.d/projects.yaml
=> Set default-branch for ansible-collection-migration/ansible-base

zuul.d/projects.yaml, zuul/tenants.yaml
Ansible Security Cisco ASA collection project
=> Defines github.com/ansible-security/ansible_collections.cisco.asa project

zuul.d/projects.yaml
Lets gate ansible-collections/openvswtch.
=> Add jobs to ansible-collections/openvswitch

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/project-config/pull/357
Depends-On: https://github.com/project-receptor/receptor/pull/141
=> Receptor: Assign templates jobs

zuul.d/projects.yaml
Lets start to integration testing for openvswitch.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/358
=> Add ansible-collections-openvswitch-openvswitch to openvswitch

github/projects.yaml, zuul/tenants.yaml
This will be managed by the network team.
=> Add support for ansible-collections/skydive

zuul.d/projects.yaml
Lets start to gate on ansible-collections/skydive.
=> Add ansible-collections/skydive testing

github/projects.yaml, zuul/tenants.yaml
=> Add ansible-collections/frr to zuul

zuul.d/projects.yaml
We are ready to gate this repo with zuul.
=> Add jobs to ansible-collections/frr

github/projects.yaml, zuul/tenants.yaml
=> Add ansible-collections/checkpoint to zuul

zuul.d/projects.yaml
We are now ready to gate our new collection.
=> Add jobs to ansible-collections/checkpoint

zuul.d/pipelines.yaml
This reverts commit 7af5b7c49170bd7942fa32f2bcbd6baff52bfb0f.
=> Revert "No longer report comments or status on check pipeline"

zuul.d/pipelines.yaml
=> Update third-party-check to use checks API

zuul.d/projects.yaml
This reverts commit aa3cff5cca5c05d5adab56d8ed4117b144ebf74e.
=> Revert "Remove ansible-tox-jobs from ansible-collections/vyos"

zuul.d/projects.yaml
Start to gate ansible-collections/asa project.
=> Add jobs to ansible-collections/asa

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/368
=> Enable ansible-collections-cisco-asa jobs

zuul.d/projects.yaml
Enable the `squash-merge` merge strategy on the Sandbox repository.
=> try merge-mode: squash-merge on sandbox

zuul.d/projects.yaml
Depend-On: https://github.com/ansible/ansible-zuul-jobs/pull/370
=> ansible/workshops: Run the workshop functional jobs

zuul.d/jobs.yaml
Tested with https://github.com/ansible/ansible-runner/pull/429
=> Switch base-minimal nodeset to centos-8

zuul.d/projects.yaml
Complete the rename, and enable gate jobs again.
=> Enable ansible-collections/cisco.asa jobs

zuul.d/projects.yaml
=> Enable ansible-collections/ansible.netcommon jobs

zuul.d/projects.yaml
=> Enable arista.eos jobs

zuul.d/projects.yaml
=> Enable jobs for ibm.qradar collection

zuul.d/projects.yaml
=> Enable ansible-collections/cisco.ios jobs

zuul.d/projects.yaml
=> Enable jobs for ansible-collections/junipernetworks.junos

zuul.d/projects.yaml
=> Enable ansible-collections/openvswitch.openvswitch jobs

zuul.d/projects.yaml
=> Enable ansible-collections/cisco.iosxr jobs

github/projects.yaml, zuul.d/projects.yaml, zuul/tenants.yaml
=> Begin rename for ansible-collections/frr

zuul.d/projects.yaml
=> Enable ansible-collections/frr.frr jobs

zuul.d/projects.yaml
This will allow to help catch breaking changes.
=> Add all network collections jobs to ansible.netcommon

github/projects.yaml, zuul.d/projects.yaml, zuul/tenants.yaml
=> Prepare rename of ansible-collections/nxos

zuul.d/projects.yaml
=> Enable ansible-collections/cisco.nxos jobs

zuul.d/projects.yaml
This reverts commit 2c1c9ed4122f89ddc5030d9819229ade744c8f6c.
=> Revert "Remove netcommon vyos jobs"

zuul.d/projects.yaml
=> Add nxos jobs

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/434
=> Add back unit testings for network collections

github/projects.yaml, zuul/tenants.yaml
Add ansible-collections/splunk.enterprise_security project.
=> add ansible-collections/splunk.enterprise_security

zuul.d/projects.yaml
Needed-By: https://github.com/ansible/ansible-lint/pull/775
=> Remove py35 jobs from ansible-lint

playbooks/base-minimal-test/post-logs.yaml
This should reduce the amount of storage we are using.
=> Expire swift logs after 3 months

zuul/tenants.yaml
Split out from https://github.com/ansible/project-config/pull/452/
=> non-gate community.general

playbooks/base-minimal-test/post-logs.yaml
This should make swift more happy.
=> Eanble zuul_log_path_shard_build for base-minimal-test

playbooks/base-minimal-test/post-logs.yaml
=> Set zuul-log-path before upload-logs-swift role

playbooks/ansible-collection/post.yaml, playbooks/ansible-collection/run.yaml
This brings our code path in line with build-ansible-collection job.
=> Refactor release ansible-collection jobs

zuul/tenants.yaml
=> Add ansible/galaxy-importer to zuul tenant

playbooks/build-ansible-collection/run.yaml
=> Activate venv for galaxy-importer

tools/zuul-projects-checks.py
This is a partial revert as it blocks us adding new projects.  The
proposed fix, needs to take into account new projects that are added
into zuul, but not loaded.  One way to do that is curl zuul.a.c, to see
if a project is loaded or not.
This reverts commit a6e7c6e7ee26155d63597b651e2495e05155b149.
=> Partial Revert "ensure all github projects have correct template"

github/projects.yaml, zuul/tenants.yaml
This is to test github enterprise, and if zuul works.
Depends-On: https://github.com/ansible/project-config/pull/466
=> Add EducationSwing/zuul-test repo for testing

zuul.d/projects.yaml
=> Add EducationSwing/zuul-test jobs

zuul.d/projects.yaml
We want to squash-merge for ansible-collections.
=> Set merge-mode on ansible-collections namespace

zuul.d/projects.yaml
ansible-zuul is a maintainer of this projects on pypi
=> ansible-builder: Add publish-to-pypi job

zuul.d/projects.yaml
=> Add ansible-collections-frr-frr-units to frr.frr

zuul.d/projects.yaml
=> Enable unit tests on netcommon

zuul.d/projects.yaml
=> Add ansible-galaxy-importer to community.general

github/projects.yaml, zuul/tenants.yaml
=> Add ansible.posix to zuul tenant

zuul.d/projects.yaml
Start the process to gate ansible.posix in zuul.
=> Add gate jobs to ansible-collections/ansible.posix

zuul.d/projects.yaml
=> Add publish jobs for ansible.posix

zuul.d/secrets.yaml
This now uses the ansible-zuul service account, over personal token.
=> Rotate ansible_automation_hub_secret token

zuul.d/projects.yaml
=> Publish frr to automation hub

zuul.d/projects.yaml
=> Publish openvswitch to automation hub

zuul.d/projects.yaml
=> Publish ibm.qradar to automation hub

zuul.d/projects.yaml
=> Publish splunk.es to automation hub

github/projects.yaml, zuul/tenants.yaml
Add community.asa to galaxy via zuul github/projects.yaml and zuul/tenants.yaml
=> Add community.asa to galaxy via zuul github/projects.yaml and zuul/tenants.yaml

zuul.d/projects.yaml
=> Publish ansible.posix to automation hub

zuul.d/projects.yaml
Enable tag-based release publishing for AWS collections
=> Enable collection publishing for AWS collections

zuul.d/projects.yaml
=> Add ansible-collections-ansible-posix-units project-template

zuul.d/projects.yaml
This reverts commit 454081e2c6601a6f4059f8dbeda269f1fa40c44e.
=> Revert "Add project-templates to aws collections"

zuul.d/projects.yaml
Add community.asa to galaxy via zuul.d projects.yaml
=> Add community.asa to galaxy via zuul.d projects.yaml

zuul/tenants.yaml
See: https://github.com/ansible/ansible-zuul-jobs/pull/520/files#r438320323
=> add vcsim to tenants.yaml

zuul.d/projects.yaml
=> Publish arista.eos to automation hub

zuul.d/projects.yaml
=> Publish cisco.asa to automation hub

zuul.d/projects.yaml
=> Publish cisco.iosxr to automation hub

zuul.d/projects.yaml
=> Release cisco.nxos to automation hub

zuul.d/projects.yaml
=> Publish vyos.vyos to automation hub

zuul.d/projects.yaml
=> Publish cisco.ios to automation hub

zuul.d/projects.yaml
=> Publish junipernetworks.junos to automation hub

github/projects.yaml, zuul/tenants.yaml
=> Add ansible-collections/symantec.epm to zuul tenant

zuul.d/projects.yaml
=> Add gate jobs for ansible-collections/symantec.epm

zuul.d/projects.yaml
=> Add more jobs to symantic.epm

zuul.d/projects.yaml
Update all community.* collections to use our new project-template.
=> Switch to publish-to-galaxy-3pci project-template

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/564
=> Add more jobs to community.asa

zuul.d/projects.yaml
Right now, we do not plan to gate it.
=> Move community.aws to 3pci

README.rst
Detail the two step process to add a new Repo into Zuul
=> README: How to on-board

github/projects.yaml
AWS collections use projects, enable in project config
=> AWS collections use projects, enable in project config

github/projects.yaml
=> Fix projects that don't have master default-branch

zuul.d/projects.yaml
=> Update ibm.qradar default-branch to main

tools/zuul-projects-checks.py
This is the first step to help keep both files in sync foe
default-branch.
=> Add default-branch check for zuul projects

github/projects.yaml, zuul.d/projects.yaml
Signed-off-by: Adam Miller <admiller@redhat.com>
=> change default branch for ansible.posix to main

github/acls/ansible-collections/symantec.epm.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for symantec.epm

tools/manage-projects.py
=> Fix exception in new acl-config logic

tools/manage-projects.py
=> Allow for empty status checks in github acls

tools/manage-projects.py
We didn't actually use the config setting before, now we do.
=> Fix another bug with acl-config

github/acls/ansible-collections/openvswitch.openvswitch.config, github/projects.yaml, zuul.d/projects.yaml
=> Rename openvswitch.openvswitch default-branch

github/acls/ansible-collections/community.asa.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for community.asa to main

github/acls/ansible-collections/vmware.config, github/projects.yaml, zuul.d/projects.yaml
Switch from `master` to `main`.
=> switch default branch of vmware collection

github/acls/ansible-collections/arista.eos.config, github/projects.yaml, zuul.d/projects.yaml
=> Update ansible-collections/arista.eos default branch

zuul.d/pipelines.yaml
Adjusted from https://semver.org/. I've removed the build part (`+...`).
=> Use proper regular expressions for semantic versioning (release and prerelease)

github/acls/ansible-collections/cisco.asa.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for cisco.asa

github/acls/ansible-collections/cisco.ios.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for cisco.ios

github/acls/ansible-collections/cisco.iosxr.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for cisco.iosxr

github/acls/ansible-collections/cisco.nxos.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for cisco.nxos

github/acls/ansible-collections/junipernetworks.junos.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for junipernetworks.junos

github/acls/ansible-collections/frr.frr.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for frr.frr

github/acls/ansible-collections/ansible-netcommon.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for ansible.netcommon

github/acls/ansible-collections/vyos.vyos.config, github/projects.yaml, zuul.d/projects.yaml
=> Update default-branch for vyos.vyos

zuul.d/projects.yaml
This will help us catch more issues before merging PRs.
=> Add arista.eos to ansible.netcommon collection

playbooks/generate-ansible-collection/pre.yaml, zuul.d/jobs.yaml
This is a much larger change than expected. Lets revert this commit, and
find another solution.
This reverts commit 4bc5062d5da1fe3828795d2e583f233de84727a6.
=> Revert "add generate-and-build-ansible-collection"

zuul.d/projects.yaml
This reverts commit 85cded6eb08e33a0af74ca558432332e4a3b0435.
=> Revert "Add cisco.asa jobs to ansible.netcommon"

zuul.d/secrets.yaml
This is to help debug upload failures to the service.
=> Rotate automation hub token

zuul.d/pipelines.yaml
=> Send email on release pipeline failures

zuul.d/pipelines.yaml
=> Test we can send an email on post pipelines

zuul.d/pipelines.yaml
This reverts commit d14ad646970f7b29f7b4e231300fa9ee0b860e18.
=> Revert "Test we can send an email on post pipelines"

zuul.d/pipelines.yaml
=> Also email successful jobs in release pipeline

zuul.d/projects.yaml
=> Add vyos.vyos jobs to ansible.netcommon

zuul/tenants.yaml
Ref: https://github.com/ansible-collections/community.kubernetes/issues/43
=> Add community.kubernetes to tenants.yaml

zuul.d/projects.yaml
Once https://github.com/ansible/project-config/pull/579 has been merged
=> community.okd project

zuul/tenants.yaml
=> tenant: add cloud.common

github/projects.yaml, zuul.d/projects.yaml
Initial configuration for the new `cloud.common` collection.
=> add the cloud.common repository

playbooks/ansible-changelog-fragment/run.yaml
=> Add failed_when statement to ansible-changelog-fragment

playbooks/ansible-changelog-fragment/run.yaml, zuul.d/jobs.yaml
=> Fix typo in fail message

zuul.d/projects.yaml, zuul/tenants.yaml
Related: https://github.com/ansible/ansible-lint/issues/1002
=> Remove ansible-lint from zuul

zuul.d/jobs.yaml
=> Add more irrelevant-files for ansible-changelog-fragments

github/acls/ansible-collections/vmware_rest.config, github/acls/ansible-collections/vmware_rest_code_generator.config
Cover the following project:
- ansible-collection/vmware_rest
- ansible-collection/vmware_rest_code_generator
=> add acl configuration for vmware_rest projects

github/acls/ansible-collections/community.yang.config, github/projects.yaml, zuul/tenants.yaml
=> Add community.yang collections

zuul.d/projects.yaml
=> Define project for community.yang

github/acls/ansible-collections/community.vmware.config, github/acls/ansible-collections/vmware.vmware_rest.config, github/projects.yaml, zuul/tenants.yaml
`vmware` → `community.vmware`
`vmware_rest` → `vmware.vmware_rest`
=> define the vmware projects with the new names

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/639
Added community.yang integration jobs.
=> Add community.yang integration jobs

github/projects.yaml, zuul.d/projects.yaml, zuul/tenants.yaml
Disabled CI on ansible-network/yang
=> Remove ansible-network.yang

github/acls/ansible-collections/trendmicro.deepsec.config, github/projects.yaml, zuul/tenants.yaml
=> Add trendmicro.deepsec to CI

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/656
=> Add project template for trendmicro.deepsec

zuul.d/projects.yaml
=> Add units to trendmicro.deepsec collection

github/projects.yaml, zuul.d/projects.yaml, zuul/tenants.yaml
This is no longer needed and can be retired.
=> Retire ansible-network/yang project

zuul.d/projects.yaml
=> Add default branch to pylibssh

zuul.d/projects.yaml
Apply `ansible-collections-cloud-common` on the `cloud.common` project.
=> apply the new template on cloud.common

github/acls/ansible-collections/ansible.network.cfg, github/projects.yaml, zuul/tenants.yaml
Add a new collection ansible.network to project-config
=> Add ansible.network collection

zuul.d/projects.yaml, zuul/tenants.yaml
=> Added config for community.molecule collection

zuul.d/projects.yaml
https://github.com/ansible-collections/community.molecule/
=> Enable community.molecule releases

playbooks/ansible-collection/twitter.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
We'll use this when we want to announce a collection release.
=> Create release-ansible-collection-announcement job

github/acls/ansible-collections/ansible.utils.config, github/projects.yaml, zuul/tenants.yaml
=> Add ansible.utils collection

zuul.d/projects.yaml
=> On board ansible.utils project

playbooks/ansible-collection/twitter.yaml
Switch away from tox to virtualenv directly.
=> Fix twitter release job

zuul.d/projects.yaml
=> Onboard rest of ansible.utils jobs

playbooks/ansible-collection/twitter.yaml
=> Fix another typo in twitter release job

zuul.d/projects.yaml
=> Add ansible.utils integration job

zuul.d/jobs.yaml
=> Promote base-minimal-test change

zuul.d/projects.yaml
This reverts commit d5ccd3e3f16e9cb6c51a147b2e7d133deb22ba15.
=> Revert "Add ansible-runner-container-image-jobs to ansible-runner"

playbooks/container-image/upload.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/722
=> Add ansible-upload-container-image job

zuul.d/projects.yaml
Removing the integration and unit test jobs. They will be added back once the tests are created.
=> Removed trendmicro.deepsec jobs

zuul.d/projects.yaml
=> Add unit test jobs trendmicro.deepsec

zuul.d/pipelines.yaml
This is an experimental pipeline where we can test out new lgtm jobs.
=> Add lgtm pipeline

zuul.d/pipelines.yaml
=> Remove status in lgtm pipeline

zuul.d/pipelines.yaml
=> Switch back to status for lgtm pipeline

github/acls/ansible/python-builder-image.config, github/projects.yaml, zuul/tenants.yaml
=> Add ansible/python-builder-image to ansible zuul tenant

zuul.d/projects.yaml
=> Add jobs to ansible/python-builder-image

github/acls/ansible/python-base-image.config, github/projects.yaml, zuul/tenants.yaml
=> Add ansible/python-base-image project

zuul.d/projects.yaml
=> Add ansible/python-base-image jobs

playbooks/ansible-collection/twitter.yaml
=> Update twitter announce grammar

github/acls/ansible-collections/aws_management.config, github/projects.yaml
This repo will house things like IAM policies and resource lifecycle management lambda.
=> Create new repo for management of Network's AWS account

zuul/tenants.yaml
Adding new repo to tenants.yml, related to #688
=> New aws_management repo. PR1

github/projects.yaml
=> Remove acl-config from ansible-network/aws_management

zuul.d/projects.yaml
=> Add jobs to ansible-network/aws_management

github/acls/ansible/awx-ee.config, github/projects.yaml, zuul/tenants.yaml
We'll be use zuul for CI on this project.
=> Add ansible/awx-ee to zuul

zuul.d/projects.yaml
This allows us to start gating the project.
ASigned-off-by: Paul Belanger <pabelanger@redhat.com>
=> Add system-required project-template to ansible/awx-ee

github/acls/ansible/network-ee.config, github/projects.yaml, zuul/tenants.yaml
We'll be using this project to create ansible network execution
environments.
=> Add ansible/network-ee to zuul

zuul.d/projects.yaml
=> Add gate jobs for ansible/network-ee

github/projects.yaml, tools/manage-projects.py
This adds support to manage the 'homepage' on GitHubs UI.
=> Update homepage for ansible/python-builder-image on github

tools/manage-projects.py
=> Fix bug with homepage setting

tools/manage-projects.py
=> Homepage is a string, not None

github/projects.yaml
=> Add quay.io links for a few projects

playbooks/build-python-tarball/run.yaml
=> Fix bug in release_poetry_project job

github/acls/ansible/ansible-core-image.config, github/projects.yaml, zuul/tenants.yaml
We'll be using this image as a parent to ansible-runner.
=> Add ansible/ansible-core-image to zuul

github/projects.yaml
=> Update homepage for ansible-core github

zuul.d/projects.yaml
=> Gate ansible/ansible-core-image in zuul

github/acls/ansible/cloud-ee.config, github/projects.yaml, zuul.d/projects.yaml
`ansible/cloud-ee` is the Execution Environment for the Ansible Cloud
Collections.
=> add ansible/cloud-ee project

github/projects.yaml
- suggest the `main` branch
- don't turn `archived` on
=> github/projects.yaml: use better values in the example

zuul.d/jobs.yaml
Let see if this is actually needed.
=> Remove requires: container-image

zuul.d/projects.yaml
We also want to rebuild ansible-runner, when code is merged to
ansible/ansible devel.
=> Add ansible-runner build image for ansible/ansible

playbooks/buildset-registry/pre.yaml
This reverts commit 3ced7f7b96f79f0a0f081ee4cf4ffed594238e0e.
=> Revert "Allow jobs to toggle pulling from intermediate registry"

zuul.d/projects.yaml
=> Add network-ee jobs to cisco.ios collection

zuul.d/projects.yaml
We are ready to switch to EEs for testing.
=> Add network-ee jobs to ansible.utils

zuul.d/secrets.yaml
For some reason, this token keeps expiring on us.
=> Rotate AH secret again

playbooks/base-minimal-test/pre.yaml, roles/add-build-sshkey-fork/README.rst, roles/add-build-sshkey-fork/tasks/create-key-and-replace.yaml, roles/add-build-sshkey-fork/tasks/main.yaml, roles/add-build-sshkey-fork/tasks/remote-linux.yaml, roles/add-build-sshkey-fork/tasks/remote-windows.yaml, roles/add-build-sshkey-fork/vars/main.yaml
Set ssh_key_algorithm and ssh_key_size to support FIPS testing.
=> Add ecdsa key to support FIPS testing

playbooks/base-minimal-test/post-ssh.yaml, roles/remove-build-sshkey-fork/README.rst, roles/remove-build-sshkey-fork/defaults/main.yaml, roles/remove-build-sshkey-fork/tasks/main.yaml
=> Modified  remove-build-sshkey to support different key types

zuul/tenants.yaml
We plan to gate this collection with zuul.
=> Promote community.aws to first party

zuul.d/pipelines.yaml
=> Email on failure for periodic jobs

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/778
=> Add smart_mgmt workshop testing

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/783
=> Add projects to integrated-vmware queue

zuul.d/projects.yaml
We are refactoring support for ubi8.
=> remove ansible post jobs

zuul.d/secrets.yaml
Temporarily add my personal ansible-core-ci key, it will be later
replaced by a new key.
=> secret: add an ansible_core_ci key

playbooks/ansible-core-ci/pre.yaml, roles/ansible-core-ci-session/defaults/main.yaml, roles/ansible-core-ci-session/tasks/main.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
This role contacts the core CI end-point to request a new (aws/sts) session.
=> add ansible-core-ci role

playbooks/ansible-collection/twitter.yaml
=> Changelogs are top level folder now

playbooks/ansible-collection/twitter.yaml
=> Use @ansible for twitter

zuul.d/projects.yaml
=> Add network-ee project template to vyos

playbooks/build-ansible-collection/pre.yaml, playbooks/build-ansible-collection/run.yaml
=> Move ensure-tox before we revoke-sudo

zuul.d/projects.yaml
Apply the `ansible-collections-community-aws` and `ansible-collections-community-aws` templates.
=> Apply the new templates on the AWS collections

zuul.d/projects.yaml
=> Add network-ee jobs to nxos and ovs

zuul.d/projects.yaml
Add network-ee jobs for iosxr
for utils jobs are already there.
=> Add network-ee jobs for iosxr

playbooks/base-minimal-test/pre.yaml
=> Try generating both rsa / ecdsa keys

zuul.d/projects.yaml
=> Add network-ee to Junipernetworks

github/README.rst
=> Add README.rst for repo / branch protection creation

github/acls/ansible-network/ansible_content_collections_metrics.config, github/projects.yaml, zuul/tenants.yaml
- adding entry to github/projects.yaml
- adding branch protection
=> adding ansible_content_collections_metrics project

github/README.rst
=> updating header

github/acls/ansible/ansible-navigator.config, github/projects.yaml, zuul/tenants.yaml
=> Add ansible-navigator project

github/acls/ansible/ansible-navigator.config, github/projects.yaml, zuul/tenants.yaml
Reverts ansible/project-config#778
=> Revert "Revert "Add ansible-navigator project""

zuul.d/projects.yaml
=> Add project-template for ansible-navigator

zuul.d/projects.yaml
=> Add ansible-navigator-jobs

zuul.d/projects.yaml
Set ansible-navigator to squash-merge.
=> nav squash

zuul/tenants.yaml
=> Added 'servicenow.itsm' to tenants

zuul/tenants.yaml
=> Minor change in servicenow.itsm tenant

github/acls/ansible-collections/servicenow.itsm.config, zuul.d/projects.yaml
=> Added 'servicenow.itsm' in projects

playbooks/base-minimal-test/post-ssh.yaml
=> Remove fork role from base-minimal-test

playbooks/base-minimal/pre.yaml
The changes are already available in base-minimal-test. This PR makes the changes available in base-minimal.
=> Generate both RSA and ECDSA keys - base-minimal

zuul.d/projects.yaml
Follow-up to #793
CC @gundalow
=> Allow to publish community.dns

zuul.d/projects.yaml
=> Add sanity test for servicenow.itsm

zuul.d/projects.yaml
=> Set squash-merge for ansible/ansible-zuul-jobs

github/acls/ansible/ansible-zuul-jobs.config, github/projects.yaml
=> Add ansible/ansible-zuul-jobs to github manage

zuul.d/projects.yaml
=> Add ansible.network to integrated-queue

zuul.d/projects.yaml
Use amazon.aws's template, not the one from community.aws.
=> test amazon.aws with the right template

playbooks/base-minimal/pre.yaml
=> Set rsa key size to 2048 in base-minimal

zuul.d/projects.yaml
=> Add network-ee container jobs to frr.frr

zuul.d/projects.yaml
=> Add network-ee jobs to cisca.asa collection

zuul.d/projects.yaml
=> Add network-ee jobs to ansible.posix

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/network-ee/pull/67
=> Add network-ee jobs to servicenow.itsp

zuul.d/projects.yaml
=> Add network-ee jobs to cloud.common

zuul.d/secrets.yaml
We've got now a dedicated account for Zuul-CI. Thanks Mark Chappell and
Sam Doran.
=> ansible-core-ci.key rotation

playbooks/buildset-registry/pre.yaml, playbooks/buildset-registry/run.yaml
=> Don't run buildset-registry on appliances

zuul.d/projects.yaml
=> anisble-python-jobs added to ansible.network

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/935
=> community.kubernetes: apply the job template

zuul.d/projects.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/940
=> okd: apply the templates

github/acls/ansible-network/releases.config, github/projects.yaml
=> Add ansible-network/releases to github/projects.yaml

github/projects.yaml, zuul.d/projects.yaml
=> Update splunk.es to use main as default branch

playbooks/ansible-changelog-fragment/run2.yaml, zuul.d/jobs.yaml
This should address multiple commits of changelog entries.
=> Add ansible-changelog-fragment2 job

zuul.d/projects.yaml
=> To enable ee over Cisco ASA

github/acls/ansible-collections/ansible.security.config, github/projects.yaml, zuul.d/projects.yaml, zuul/tenants.yaml
Add ansible.security meta collection to project-config
=> Add ansible.security meta collection

zuul.d/projects.yaml
Add ansible-collections/ansible.security jobs
=> Add ansible-collections/ansible.security jobs

zuul.d/projects.yaml
PR to add ansible.security to integrated-queue
=> PR to add ansible.security to integrated-queue

zuul.d/secrets.yaml
=> Rotate automation hub token again

zuul.d/pipelines.yaml
This is a shot in the dark to see if we can get gate working again.
=> Try dropping [bot] from status checks

zuul/tenants.yaml
=> Add ansible-collections/ansible.windows to zuul tenant

zuul.d/pipelines.yaml
Lets give this a shot to see if we properly enqueue PRs into gate.
=> Trigger gate pipeline off check_run events

zuul.d/pipelines.yaml
=> Remove unused trigger for gate pipeline

github/acls/ansible/network-ee.config
=> Prepare ansible/network-ee to drop clean check requirement

zuul.d/pipelines.yaml
=> Fix superceeds syntax for gate pipeline

github/acls/ansible/project-config.config, github/projects.yaml
=> Manage ansible/project-config branch protections

zuul.d/projects.yaml
PR to add EE jobs for security supported platforms
=> PR to add EE jobs for security supported platforms

zuul.d/pipelines.yaml
=> Update 3pci-check pipeline to use check_run API

zuul.d/projects.yaml
=> Add jobs to pabelanger/pabelanger-sandbox1

README.rst
See https://github.com/ansible/community/issues/613
=> Update irc server

zuul/tenants.yaml
=> Added 'kubernetes.core' to tenants

github/acls/ansible-network/windmill-config.config
=> Add ACLs file for ansible-network/windmill-config

zuul.d/projects.yaml
=> Add sanity test for kubernetes.core

github/acls/ansible-network/network-runner.config, github/projects.yaml
=> Manage ansible-network/network-runner branches

zuul.d/projects.yaml
=> kubernetes.core: Enable EE tests

zuul.d/projects.yaml
Reverts ansible/project-config#877
=> Revert "kubernetes.core: Enable EE tests"

zuul.d/pipelines.yaml
=> Experiment with leaving review on a PR

zuul.d/pipelines.yaml
=> Add missing review-body for lgtm pipeline.

zuul.d/pipelines.yaml
This reverts commit 6bef9cb22ea83493b971d693ae5e0a1bca76884e.
=> Revert "Revert "Promote LGTM logic to gate pipeline""

zuul.d/pipelines.yaml
Switch lgtm pipeline to checks API
Revert "Revert "Revert "Promote LGTM logic to gate pipeline"""
=> Pull request for master

zuul.d/pipelines.yaml
Make this work a little like the gate pipeline, as not to spam comments
from the ansible-zuul[bot].
=> Refactor lgtm pipeline

zuul.d/pipelines.yaml
=> Trigger gate on pull_request_review too

zuul.d/pipelines.yaml
=> Don't comment on lgtm pipeline for success

zuul.d/pipelines.yaml
This should cut down on the spam comments from lgtm pipeline.
=> Don't run lgtm jobs, if we've already left a review

zuul.d/pipelines.yaml
=> Try escaping [bot]

zuul/tenants.yaml
=> Remove duplicate kubernetes.core reference

zuul.d/projects.yaml
Added EE tests for the following collection -
* amazon.aws
* vmware.vmware_rest
=> Added EE tests

zuul.d/projects.yaml
This reverts commit aa1fdc8669ea74c752c528f23cfe1b8f28abe089.
We need to get additional packages added to the environment to support several of the AWS unit tests
See https://dashboard.zuul.ansible.com/t/ansible/build/b678d1d315ed4c089502882b25ea0367
And https://dashboard.zuul.ansible.com/t/ansible/buildset/51cd5437940343d98acacb79a6729522
=> Revert "Added EE tests"

zuul.d/projects.yaml
This reverts commit a06edd766265e2cd305d111d616b1d97205def2b.
=> Revert "Remove release-ansible-collection-announcement job"

zuul.d/pipelines.yaml
=> Actually, don't enqueue check failures to gate

zuul.d/pipelines.yaml
=> Remove status check for gate

zuul.d/pipelines.yaml
=> Take 2 for ansible/check requirement

zuul.d/pipelines.yaml
This reverts commit 73c71860076ac8db4b2bb0865a44acaa44bd8757.
=> Revert "Take 2 for ansible/check requirement"

zuul.d/jobs.yaml
=> Migrate build-ansible-collection to centos-8-stream

zuul.d/pipelines.yaml
This reverts commit 19d014ac31ca4372e69b07134a2a8d9232086c2a.
=> Revert "Reorder gate to see if sempahore works better"

zuul.d/pipelines.yaml
This reverts commit 0ca886f6e3f05252795b11bfcc808bd62cfaca29.
=> Revert "Remove check_run trigger for gate pipeline"

zuul.d/pipelines.yaml
Along with reorder the ondemand pipeline in the UI.
=> Remove experimental pipeline

zuul.d/pipelines.yaml
This is left over from days past and nothing is using it.
=> Remove merge-check pipeline

tools/zuul-projects-checks.py
Use the `gh` CLI tool to query Github API to get the right default branch. Use this information to compare wit the local  configuration.
Also properly compare the name of the repository, ansible-community/molecule is in github.com/ansible-community/molecule-libvirt but are not the same.
Finally use an emoji to mark the sections instead of a series of '='. Those where getting too long.
=> use gh to compare Github branch configuration

github/projects.yaml, zuul/tenants.yaml
The project does not use molecule anymore.
=> remove ansible-community/molecule

github/projects.yaml
Partial reverse of https://github.com/ansible/project-config/pull/934
See: https://github.com/ansible/project-config/pull/934#discussion_r705495040
=> github: openshift/community.okd is not managed by us

zuul.d/projects.yaml, zuul/tenants.yaml
The project location has changed to github.com/openshift/community.okd
=> remove the old community.okd project

zuul/tenants.yaml
Add community.healthchecksio to tenants.yaml
Relates to https://github.com/ansible-collections/overview/issues/184#issuecomment-918158441
=> Add community.healthchecksio to tenants.yaml

zuul.d/projects.yaml
Relates to https://github.com/ansible-collections/overview/issues/184#issuecomment-918158441
Recheck and merge after https://github.com/ansible/project-config/pull/942 is merged
=> Add community.healthchecksio to zuul.d/projects.yaml

zuul.d/projects.yaml
Disable `network-ee-tests` for `kubernetes.core`
=> Disable network-ee-tests for kubernetes.core

zuul.d/projects.yaml
Add `publish-to-automation-hub` for `kubernetes.core` and `community.okd`
=> Add publish-to-automation-hub for kubernetes.core and community.okd

zuul.d/projects.yaml
=> [ansible.network] update meta job template

zuul.d/projects.yaml
Moving these to another CI system
=> Remove jobs from ansible-builder

zuul.d/projects.yaml
This reverts commit 86ebc7336f99bf2829dbb3faf4d37593ba5c3282.
=> Revert "Disable network-ee-tests for kubernetes.core"

zuul/tenants.yaml
zuul/tenants.yaml: Add community.cockroachdb
=> zuul/tenants.yaml: Add community.cockroachdb

zuul.d/projects.yaml
Recheck and merge after https://github.com/ansible/project-config/pull/968
=> zuul.d/projects.yaml: Add community.cockroachdb

.gitignore, .yamllint, playbooks/configure-tox-with-gh-cli/pre.yaml, tools/zuul-projects-checks.py, zuul.d/jobs.yaml, zuul.d/secrets.yaml
add ability to authenticate on github
=> Use the CI to ensure all the default-branch are properly set

playbooks/configure-tox-with-gh-cli/pre.yaml
=> fix missing variable from non voting job

zuul.d/secrets.yaml
add new permanent token for CI testing
=> gh token update

zuul/tenants.yaml
=> Add aap-azure-billing to zuul tenant

zuul/tenants.yaml
This reverts commit f2a99a8a8b0d49cb4ebf88437224cc0a46ef4ce9.
=> Revert "Add aap-azure-billing to zuul tenant"

github/acls/ansible-network/k8s-node-pool-config.config, github/projects.yaml, zuul/tenants.yaml
This project will be used to build a container image used
by k8s DaemonSet.
=> Add ansible-network/k8s-node-pool-config

github/projects.yaml
We lost access for some reason.
=> Disable github ansible-builder

github/acls/ansible-network/k8s-node-pool-config.config
=> Fix branch name for k7s-node-pool-config

zuul/tenants.yaml
https://github.com/ansible-collections/overview/issues/188#issuecomment-995041570
=> zuul/tenants.yaml: add community.sap

zuul.d/projects.yaml
https://github.com/ansible-collections/overview/issues/188#issuecomment-995041570
Recheck and merge after https://github.com/ansible/project-config/pull/996
=> zuul.d/projects.yaml: add community.sap Galaxy publishing

zuul.d/projects.yaml
Remove junos stable-211 jobs from netcommon
=> Add ansible-collections-juniper-junos-netcommon-jobs template

zuul.d/projects.yaml
removal of ovs jobs from netcommon project
=> removal of ovs jobs from netcommon project

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/277
=> ansible.windows is now on SoftwareFactory

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/279
=> servicenow.itsm is on SF now

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/281
=> ansible.posix is on SF now

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/283
=> migrate skydive

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/285
=> ids_{config,install} moved on SF

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/286
=> move more jobs on SF

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/284
=> migrate ansible-network/network-runner

zuul.d/projects.yaml
Moved on SoftwareFactory.
See: https://github.com/ansible/zuul-config/pull/287
=> add ansible/python-{base,builder}-image

zuul.d/projects.yaml
=> Removed ansible-collections-juniper-junos-netcommon template

zuul.d/projects.yaml
=> Add ansible-collections-ansible-netcommon project template

zuul.d/projects.yaml
- community.aws
- amazon.aws
- vmware.vmware_rest
=> set noop-jobs template to some migrated projects

github/acls/ansible-collections/ansible.plugin_builder.config, github/projects.yaml, zuul/tenants.yaml
=> Add ansible.plugin_builder

github/acls/ansible-community/ansible.plugin_builder.config, github/projects.yaml, zuul/tenants.yaml
=> Update plugin_builder references

github/acls/ansible-community/ansible.plugin_builder.config
=> [plugin_builder] Add check pipeline

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/345
=> checkpoint is fully migrated

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/347
=> juniper.junos is fully migrated

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/348
See: https://github.com/ansible-collections/symantec.epm/pull/10
=> symantec.epm is fully migrated

zuul.d/projects.yaml
This is the counterpart to https://github.com/ansible/zuul-config/pull/362
=> Remove netcommon tests

zuul.d/projects.yaml
See: https://github.com/ansible/zuul-config/pull/368
=> security collections are now fully migrated

README.rst
See: https://github.com/ansible/zuul-config
=> project-config is deprecated
