zuul.d/projects.yaml

While we have no testing, we can start gating ansible/project-config. No
longer manually merging of code.

Add noop jobs

---

playbooks/base-minimal-test/pre.yaml

To make our logs a little nicer, we can now use logs.zuul.ansible.com
reverse proxy.

bast-minimal-test: use logs.zuul.ansible.com swift proxy

---

playbooks/base-minimal-test/post-logs.yaml

We don't want to return the URL from swift, we want to inject our own.

Try to override upload-logs-swift logs url

---

zuul.d/jobs.yaml

Remove ubuntu-bionic, in favor of centos-7.

base-minimail-test: switch to centos-7-1vcpu nodeset

---

zuul.d/projects.yaml

These jobs are now defined in tree.

Remove project stanza for ansible-network/windmill-config

---

zuul.d/projects.yaml

Start gating packet-ci-cloud with zuul.

Add noop jobs for ansible-network/packet-ci-cloud

---

zuul.d/projects.yaml

This is so, after we approve changes to our zuul tenant configuration,
they will go live.
Depends-On: https://github.com/ansible-network/windmill-config/pull/307

Run windmill-config-deploy promote job on ansible/project-config

---

zuul.d/projects.yaml

Now that ansible-network/juniper_junos is added to our zuul tenant, we
can start running gate jobs again on it.

Add jobs for ansible-network/juniper_junos

---

zuul.d/projects.yaml

We only need to promote a change, if we modify zuul/tenants.yaml.

Limit when we run windmill promote job

---

zuul.d/projects.yaml

This allows us to gate the project.

Add noop-jobs to ansible-network/aws project

---

zuul/tenants.yaml

We want to add ansible/ansible-runner to zuul.ansible.com, but not load
any jobs from it for now. This will allow us to do cross-project testing
to help the migration from sf.io.

Add ansible/ansible-runner to ansible zuul tenant

---

zuul/tenants.yaml

We want to gate this project with zuul.

Add ansible-network/network-runner to ansible zuul tenant

---

zuul/tenants.yaml

Add ansible-network/linux_network to ansible zuul tenant

---

zuul/tenants.yaml

We'll be gating this project using zuul.

Add ansible-network/network_configurator to ansible zuul tenant

---

zuul/tenants.yaml

We plan on gating this repo with zuul.

Add ansible-network/net_operations to ansible zuul tenant

---

zuul/tenants.yaml

We plan on gating PRs with zuul.

Add ansible-network/configure-vlan to ansible zuul tenant

---

zuul/tenants.yaml

Add ansible-network/content_store to ansible zuul tenant

---

zuul.d/projects.yaml

We are no longer going to run jobs on these projects, so stop running
noop jobs.

Remove retired cloud_vpn roles from zuul

---

zuul.d/projects.yaml

We've retired this project, next step is to remove it from our tenant
configuration for zuul.

Remove ansible-network/net_operations jobs

---

zuul.d/projects.yaml

This gives us python3, which is what everything should be using now.

Switch ansible/project-config to use ansible-python-jobs

---

tox.ini

We want all things to be using python3.

Default basepython to python3 for tox.ini

---

zuul.d/projects.yaml

Now that ansible/ansible-runner has our github app installed, we can
start to run some check jobs.

Bring online jobs for ansible/ansible-runner

---

zuul.d/projects.yaml

All projects should have this.

Add system-required to ansible/project-config

---

zuul.d/projects.yaml

We want to run linting check on ansible-runner.

Add ansible-tox-linters to ansible/ansible-runner

---

zuul/tenants.yaml

We want to start gating this project with zuul.ansible.com.

Add ansible-network/vyos to ansible zuul tenant

---

zuul.d/projects.yaml

We need to add python-jobs but lets make sure branch projection is first
setup.

Add noop jobs to ansible-network/vyos

---

zuul.d/projects.yaml

This starts the process of automating the release process.

Add ansible-build-python-tarball to ansible/ansible-runner

---

zuul.d/projects.yaml

We can use our new project-template for tox python3 jobs.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/32

Switch to ansible-python3-jobs project-template

---

github/projects.yaml
zuul/tenants.yaml

We want to start managing ansible-network/yang under gitops and start
gating this repo with zuul.

Import ansible-network/yang project

---

github/projects.yaml
zuul/tenants.yaml

We want to both manage via gitops and gate jobs with zuul for
ansible-network/network-engine.

Import ansible-network/network-engine

---

zuul.d/projects.yaml

The ansible-network/vyos role depends on ansible-network/network-engine
for testing.

Set required-projects for vyos jobs

---

zuul/tenants.yaml

We want to gate this repo with zuul.

Add ansible-network/cloud_vpn to ansible zuul tenant

---

zuul/tenants.yaml

We want to demo zuul's ability to molecule team, but we also want to do
cross project testing with it. Import it into our tenant so we can start
using it.

Import ansible/molecule into ansible zuul tenant

---

zuul.d/jobs.yaml

This is a results of the openstack.org -> opendev.org migration.

Force merge opendev.org/zuul/zuul-jobs change

---

zuul/tenants.yaml

Now that we have an opendev.org connection in zuul, we can start to load
projects from it.

Add opendev.org projects

---

zuul/tenants.yaml

Now that opendev.org connection is working, we can remove these.

Remove git.o.o projects

---

zuul.d/projects.yaml

Now that tox.ini is in place for the project, we can switch from noop
jobs.

Add ansible-tox-linters to ansible/network

---

zuul/tenants.yaml

We want to start working on migrating ansible/awx to zuul.ansible.com,
but we cannot load any jobs from it, as sf.io is the gatekeeper.

Add ansible/awx to ansible zuul tenant

---

playbooks/base-minimal-test/post-ssh.yaml
playbooks/base-minimal-test/pre.yaml

This is because we likely are using network_cli.

Don't run playbooks on appliance hosts

---

zuul.d/projects.yaml

This is now confirmed to be working.

Move ansible-test-network-integration-eos to periodic pipeline

---

zuul.d/projects.yaml

We are refactoring this job, the following commit will add back a
project-template.

Remove ansible-test-network-integration-vyos jobs

---

zuul.d/pipelines.yaml

We'll be using this pipeline for 3pci testing against github.com
projects, eg: ansible/ansible.

Add third-party-check pipeline

---

zuul.d/pipelines.yaml

This allows us to report back success / failures to github.com PRs.

Add github.com reporters to third-party-check pipeline

---

zuul.d/pipelines.yaml

Now that we have our github app installed on ansible/ansible, we can
start doing pre-merge testing over this periodic pipeline.

Remove periodic-3hr pipeline

---

zuul.d/pipelines.yaml

This works just like third-party-check, but we don't report results back
to github. In this case, we want to run jobs against stable branches,
but tests are currently failing.
This is short term until we get them passing, and then we can remove.

Add third-party-check-silent pipeline

---

zuul.d/jobs.yaml

This is needed now that we have upgraded to zuul 3.9.0.

Set ara_report_executable for ara-report role

---

playbooks/base-minimal-test/post-logs.yaml

Remove ara-report-fork from base-minimal-test

---

zuul.d/jobs.yaml

This time use ansible_version to help identify the version of ansible a
job is using, over hardcoding it.

Round 2 for ara_report_executable

---

zuul.d/pipelines.yaml

We don't really have a ton of post / promote jobs in high precedence, so
bump gate up, and check too. So check isn't blocked when periodic jobs
run.

Increase precedence for check and gate

---

zuul/tenants.yaml

This onboards ansible-community/ansible-bender into zuul.ansible.com,
but doesn't load any jobs from the project. This is mostly because, we
do not want their jobs to break out tenant.

Add ansible-community/ansible-bender to ansible zuul tenant

---

playbooks/base-minimal/pre.yaml

This allows us to start using cached git repos, if setup on our images.

Promote prepare-workspace-git base-minimal-test change

---

playbooks/base-minimal-test/post-logs.yaml

This role is required for the new "Logs" tab to work on the Zuul
build page.  Test its addition to base-test.

Add Zuul manifest to base-test

---

playbooks/base-minimal-test/post-logs.yaml
playbooks/base-minimal/post-logs.yaml

This promotes the zuul-manifest role previously tested in base-test
to base.
This role is required for the new Logs tab to work on the Zuul
build page.

Add the zuul-manifest role to base

---

zuul/tenants.yaml

This should cause Zuul to now report back the build page to github
rather then logs url directly.

Enable tenant.report-build-page

---

zuul.d/pipelines.yaml

Experiment with getting github status to use our new shiny builds page.

Set status-url to buildset page for check

---

zuul.d/pipelines.yaml

Now that we have confirmed this to work, we can properly report back to
github our buildset page.

Use status-url for all pipeline reporters

---

zuul.d/projects.yaml

This drops noop-jobs as we are ready to gate on lint checks.

Switch to ansible-python-jobs for network collections

---

github/projects.yaml
zuul/tenants.yaml

This is part of our collections effort, we want to start testing
network.cli.

Add ansible-network/ansible_collections.network.cli to zuul

---

zuul.d/projects.yaml

Start gating eos, ios, iosxr and junos for network integration tests.

Add more network integration tests to collections

---

github/projects.yaml
zuul/tenants.yaml

We'll be using this to mass migrate our network collections.

Add ansible-network/network_content_collector to zuul tenant

---

playbooks/propose-github-updates/post.yaml

This otherwise, netrc doesn't work. The fix here, is to switch to SSH
keys.

Cap git-pull-request to 3.0.0

---

zuul.d/projects.yaml

These are the wrong jobs we want to test with.

Remove network.netconf integration jobs

---

playbooks/base-minimal-test/post-logs.yaml

We are dealing with POST_FAILUREs in vexxhost when uploading logs to
swift, it was suggested we try hash our logs across containers, to help
with these timeouts.
This means, we now drop logs.z.a.c from our log_url.

Partitions swift containers for logs

---

playbooks/base-minimal/post-logs.yaml

This removes using logs.z.a.c as the hostname to browse logs, it also
hashes our logs creating more swift containers.

Promote base-minimal-test changes

---

playbooks/base-minimal-test/post-logs.yaml
zuul.d/jobs.yaml
zuul.d/secrets.yaml

This will add a 2nd cloud, for logs storage, to help minimize our
POST_FAILUREs we are seeing when we have issues with swift.

Experiment using rackspace DFW for swift logs

---

github/projects.yaml
zuul/tenants.yaml

We'll be using this for our new cisco.nxos collection.

Add ansible-network/ansible_collections.cisco.nxos to zuul

---

zuul/tenants.yaml

This allows us to potentially gate ansible-bender with jobs.

Allow ansible-bender to load intree zuul.yaml files

---

zuul.d/projects.yaml

This moves our common jobs to central config.

Add linter jobs to ansible-security/ids_config

---

zuul.d/projects.yaml

Now that linter jobs are passing, and stable we can centralize this job
config.

Remove noop jobs from ansible-security/ids_install

---

playbooks/ansible-collection/post.yaml
zuul.d/jobs.yaml

This allows us to sync back the new collection to the executor, the next
step in publishing the job.

Add post-run playbook for release-ansible-galaxy-collections

---

playbooks/ansible-collection/run-pre.yaml
zuul.d/jobs.yaml

This allows us to remove hardcoded version numbers and get to a point
where we can publish latest master to galaxy.

Dynamically version our collections based on git info

---

zuul.d/projects.yaml

We are now ready to do per commit releases to ansible galaxy.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/240

Publish vyos.vyos collection to ansible galaxy

---

zuul.d/projects.yaml

Until we figure out what to do with stable branch jobs, only publish
master.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/241

Use publish-to-galaxy-master-only job for network collections

---

github/projects.yaml
zuul/tenants.yaml

Bring online ansible-security/ansible_collections.ibm.qradar for ansible
tenant, we plan to start to run more testing against it.

Add ansible-security/ansible_collections.ibm.qradar to zuul

---

github/projects.yaml
zuul/tenants.yaml

We'll be using this repo to drive our network collection migrations now.

Add ansible-network/network_collections_migration to zuul

---

zuul.d/projects.yaml

This adds noop jobs to start to gate the ibm.qradar.

Add noop jobs for ansible-security/ansible_collections.ibm.qradar

---

zuul.d/projects.yaml

Now that zuul is setup to gate the repo, using noop jobs, we can start
to publish content to galaxy.

Publish qradar collections to galaxy

---

playbooks/ansible-collection/post.yaml

This starts the process to use zuuls new artifact handler for dealing
with collection tarballs.

Return collection artifact to zuul

---

playbooks/ansible-collection/post.yaml

This will allow users to download and inspect them.

Move collection tarballs into log folder

---

zuul.d/projects.yaml

We only have a a master branch for ibm.qradar, this fixes a bug with
release / pre-release jobs only happening on master branches.

Switch ibm.qradar collection to publish-to-galaxy

---

zuul/tenants.yaml

We won't gate ansible/galaxy, but we do want to be able to run a
buildset-galaxy server.

Add ansible/galaxy to zuul ansible tenant

---

zuul/tenants.yaml

This is required for testing in collection content for ansible 2.10.

Switch to ansible-collection-migration/ansible-minimal

---

github/projects.yaml
zuul/tenants.yaml

This is now our common network collection.

Add ansible-network/ansible_collections.ansible.netcommon to zuul

---

github/projects.yaml
zuul/tenants.yaml

This fork will be used, so we can carry patches needed to produce
network collections. We'll continue to sync from upstream on a
regularly.

Add ansible-network/collection_migration into zuul

---

zuul.d/projects.yaml

This allows us to gate commits on the new repo.

Add noop jobs to ansible-network/collection_migration

---

zuul/tenants.yaml

Both pytest-molecule and selinux (shim) are usually used with module
itself, first enables pytest to detect and run scenarios as tests and
the second gives access to system selinux from inside a virtualenv,
allowing us to run ansible from isolated virtualenvs on selinux enabled
systems.
Needed-By: https://github.com/pycontribs/pytest-molecule/pull/53

Added molecule related projects to Zuul

---

zuul/tenants.yaml

The POC is over, lets remove this.

Remove metal3-io/metal3-dev-env

---

zuul/tenants.yaml

This should allow us to define jobs from inside them.

Make molecule projects trusted

---

zuul.d/projects.yaml

We now have github-workflow jobs that can gate for us, we also have
in-tree jobs.

Remove noop jobs from ansible-network/network_collections_migration

---

zuul.d/pipelines.yaml

Instead of sending user to the generic dashboard it will open the page where he can see the status of the jobs related to his change.

Correct pending status-url

---

zuul.d/projects.yaml

Bring online iosxr netconf testing for ansible.netcommon collection.

Add ansible-collections-cisco-iosxr-netconf to ansible.netcommon

---

github/projects.yaml
zuul/tenants.yaml

Now that this is retired, we can remove it from zuul.

Retire ansible-network/ansible_collections.juniper.junos

---

github/projects.yaml

This allows us to do gitops on molecule related projects.

Manage ansible-community/molecule* projcts

---

zuul.d/pipelines.yaml

Now that we know the pending status-url works, we can make the change to
all other pipelines.

Update github status-url across the board

---

zuul.d/jobs.yaml

Fedora nodes are replaced every 6 months, by moving to centos-8,
hopefully we have less churn at OS level.

Switch jobs to centos-8 over fedora-latest

---

zuul/tenants.yaml

This is because we are migrating it to another namespace.

Remove ansible/molecule from zuul

---

github/projects.yaml
zuul/tenants.yaml

Now that molecule has moved, we can onboard it into zuul.

Add ansible-community/molecule to zuul

---

zuul.d/pipelines.yaml

There was some edge cases, where we didn't properly record job failures
to the database.

Remove more pipeline failures to mysql

---

playbooks/publish/pypi.yaml
zuul.d/jobs.yaml

This should help avoid some problems we are having with twine today.

Install twine into virtualenv for pypi-upload job

---

zuul.d/jobs.yaml

Now that we know this job works as expected, we can publish to pypi
directly.
Also drop universal wheels, as some project may not support it.

Update release-ansible-python to publish to pypi.org

---

zuul.d/projects.yaml

We are ready to automate release of molecule-libvirt.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/342

Add publish-to-pypi to molecule-libvirt

---

zuul.d/projects.yaml

Attaching two new job templates for ansible-runner:
* ansible-python-jobs
* publish-to-pypi

ansible-runner: attaching new job templates

---

github/projects.yaml
zuul/tenants.yaml

Adds all molecule drivers to ansible-community as part of migrating them from their temporary location at pycontribs.

Add molecule-containers project

---

github/projects.yaml
zuul/tenants.yaml

Enable Zuul on virt-lightning/esxi-cloud-images. This repository is used
to build the ESXi cloud image.

add virt-lightning/esxi-cloud-images in Zuul

---

tools/manage-projects.py

While we supported the ability to create a project, we didn't actually
populate the repo.  For now, just use the feature in github until we can
update it with our own function.

Add auto_init to new projects we create

---

zuul.d/projects.yaml
zuul/tenants.yaml

Remove ansible-collection-migration/ansible-minimal

---

zuul/tenants.yaml

This will be online for a few more weeks, and allow us to stop building
the ansible-base tarball ourself.

Add ansible-collection-migration/ansible-base to zuul

---

zuul.d/projects.yaml

This is because the master only publish job is broken.

Update network collections to use publish-to-galaxy

---

zuul.d/projects.yaml
zuul/tenants.yaml

Adds default zuul projects from molecule drivers.

Enable zuul integration jobs on molecule drivers

---

github/projects.yaml
zuul/tenants.yaml

We don't need the repository in Zuul anymore.

remove ansible-network/ansible_collections.community.vmware

---

github/projects.yaml
zuul/tenants.yaml

We'll be using this for the openvswitch collection for ansible-network.

Add ansible-collections/openvswitch repo to zuul

---

zuul.d/pipelines.yaml

Now that zuul 3.17.0 support basic checks API for github, enable so we
can test.

Enable checks API for check pipeline

---

zuul.d/pipelines.yaml

With checks API support enable, we should no longer need to do this. As
the data is reported to checks API tab.

No longer report comments or status on check pipeline

---

zuul.d/pipelines.yaml

This is the 2nd try to remove comments from PRs in check. We still need
to set the status I believe, as we cannot require a check API yet.

Remove comments from check pipeline

---

zuul.d/pipelines.yaml

Now that we know check works properly, we can also enable it on gate.

Use checks API for gate pipeline

---

zuul.d/projects.yaml

This is because ansible/ansible devel is now frozen, so we cannot fix
issues there.  We need to allow the sync to happen, then fix the PR.

Remove ansible-tox-jobs from ansible-collections/vyos

---

zuul.d/pipelines.yaml

This is because, we still need this info for branch protections.

Add back status info for gate

---

zuul/tenants.yaml

We do not plan to gate ansible-lint right now, so for now allow us to
run check jobs.

Add ansible-lint to zuul for 3pci

---

zuul.d/projects.yaml

Because we don't gate ansible-lint, we can define the jobs for it here.

Add third-party-check for ansible-lint

---

tools/manage-projects.py

By default, now allow both merge commits and squash merging, as zuul now
supports both.

Allow squash merging for projects

---

zuul.d/projects.yaml

Use `squash-merge` merge strategy for the following projects:
- vmware
- vmware_rest

vmware: use squash-merge strategy

---

zuul.d/jobs.yaml

This allows us to prepare for changing base-minimal to use
centos-8-1vcpu which is needed for taking advantage of newer toolchain
tools in tox jobs, which use nodeset defined by base-minimal.

Switch base-minimal-test to use centos-8-1vcpu

---

zuul.d/projects.yaml

Add `publish-to-galaxy` templare to `vmware` and `vmware_rest` projects.

add publish-to-galaxy tpl to vmware projects

---

github/projects.yaml
zuul.d/projects.yaml
zuul/tenants.yaml

This will require a few commits to rename the asa repo to cisco.asa.
For now, we disable all jobs and remove it from zuul.

Begin rename of ansible-collections/asa

---

github/projects.yaml
zuul.d/projects.yaml
zuul/tenants.yaml

The new location of the repo will be
ansible-collections/ansible.netcommon.

Begin rename of ansible-collections/netcommon

---

github/projects.yaml
zuul.d/projects.yaml
zuul/tenants.yaml

These recently moved until ansible-collections namespace, so we need to
update zuul.

Update for amazon.aws and ibm.qradar collections

---

zuul.d/projects.yaml

This should make use of jobs with standard names defined in dependent change and remove the broken tox-py27 jobs which was running alongside ansible-tox-py27 one.
Before this change the list of executed jobs was ready confusing for the use due to their inconsistent names.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/398

Clean ansible-lint jobs

---

zuul.d/projects.yaml

This brings back online testing for the vyos.vyos collection.

Enable ansible-collections/vyos.vyos jobs

---

zuul.d/projects.yaml

Make sure we have openvswitch collection jobs working, before enabling
more.

Partial revert of ansible.netcommon jobs

---

github/projects.yaml
zuul/tenants.yaml

This is actually the new name of the collection.

rename splunk.enterprise_security ⭢ splunk.es

---

zuul.d/projects.yaml
zuul/tenants.yaml

Remove ansible-collection-migration/ansible-base

---

zuul.d/pipelines.yaml

Adds a periodic-weekly which is identical with the one used by openstack zuul tenant.
This can be used by projects that want to rebuild their jobs in order
to discover regressions from external sources.
This covers a gap as current two recurring pipelines run too often, which would put serious resource strains.

Add periodic-weekly pipeline

---

zuul.d/projects.yaml
zuul/tenants.yaml

Branch protections have been enabled for `community.general`.
I'm not exactly sure which `templates` to add. We are using Shippable for CI at the moment.
Do we need any Zuul configuration files adding to https://github.com/ansible-collections/community.general ?
Once this has been seen to work I'll add it for `community.*` in a follow-up PR

Enable Galaxy publish for c.general

---

playbooks/build-ansible-collection/run.yaml

This will help to confirm we can import collections into galaxy, before
uploading them.

Validate collections with galaxy-importer

---

tools/zuul-projects-checks.py
zuul.d/projects.yaml

Ensure all the projects with either `noop-jobs` or `system-required`.

ensure all github projects have correct template

---

zuul.d/projects.yaml

Activate the following jobs:
- publish-to-galaxy
- ansible-collections-security-splunk-es

splunk: enable ansible-collections-security-splunk-es

---

zuul.d/projects.yaml

Apply the `ansible-collections-security-ibm-qradar` template to
`ibm.qradar` collection.
Template tested here: https://github.com/ansible-collections/ibm.qradar/pull/17/files#diff-15014422bc6a3e78155e7f4c71f63e72

qradar: enable functional tests

---

playbooks/build-ansible-collection/run.yaml

This is going to be more complex then originally thought. The correct
way to do this, is create an ansible-galaxy-importer job, which
downloads and installs all required collections.

Revert galaxy-importer change

---

playbooks/base-minimal-test/pre.yaml

Do not run `prepare-workspace-git` role on any group of hosts with `appliance` prefix.
This is the first iteration, we for now focus on `base-minimal-test`. The second iteration
will actually touch `base-minimal`.

prepare-workspace-git: ignore appliance*

---

playbooks/base-minimal/pre.yaml

Ensure we don't run `prepare-workspace-git` on any appliance groups.
This change has been tested through
`0e1a11cce873a3a5a592f388c70ba603383b3805` and the following PR:
https://github.com/ansible/ansible-zuul-jobs/pull/489

don't run prepare-workspace-git on appliances

---

zuul.d/projects.yaml

This is so we can properly set up cross-project testing, if needed.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/534

Add project-templates to aws collections

---

zuul.d/projects.yaml
zuul/tenants.yaml

For the `community.` collections which are fully managed by the community, allow build on tag.

Add some community collections

---

zuul.d/projects.yaml

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/560

ansible-builder: Sync job verification between pyproject and setuppy

---

zuul.d/jobs.yaml
zuul.d/semaphore.yaml

Currently, AH will process collections uploads serially, in an effort to
avoid jobs waiting on AH to run ansible-test, we can rate limit jobs.

Create semaphore for ansible automation hub

---

zuul.d/projects.yaml

This is to ensure we have pre-release of ansible.netcommon installed.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/566

Add more jobs for community.asa

---

github/projects.yaml
tools/manage-projects.py

This is the first step on gitops for branch rename in github. Most
projects no longer wish to use 'master' as the default branch name. As
such, we need a way to update it.
Currently, there is no way to auto_init a repo in github using a branch
other then master.  We'll have to work around this.

Add support to change default-branch for github projects

---

github/projects.yaml

Add a header to clarify the purpose of the file, and warn about the potential impacts.

projects.yaml: add a warning header

---

github/acls/ansible-network/sandbox.config
github/projects.yaml
tools/manage-projects.py

This adds basic support to manage branch protections via git. We'll
first start testing on ansible-network/sandbox then move to other
projects.
The idea, is we drop down a .config file, if the settings we want to
enforce for each branch, on each project.  We can also include a
top-level common file, for shared projects if needed.

Initial support to manage branch protections

---

zuul.d/projects.yaml

`community.aws` is listed two times in a row.

drop duplicated entry in zuul.d/projects.yaml

---

zuul.d/projects.yaml

c.f.: https://github.com/ansible/ansible-runner/pull/471
- uses new project-template that
- .. conditionally runs py2 tox jobs against
- .. PRs for pre-2.0 branches (specifically, stable/1.3.x, stable/1.4.x)

ansible-runner jobs should default to py3

---

playbooks/ansible-collection/run-pre.yaml
playbooks/build-ansible-collection/run.yaml

This fixes the follow upstream commit:
https://opendev.org/zuul/zuul-jobs/commit/c388e61160908c001c41ae44fb51ae4be81ada45

Set tox_envlist: venv for tox role

---

playbooks/generate-ansible-collection/pre.yaml
zuul.d/jobs.yaml

`generate-and-build-ansible-collection` is a new job based on
`build-ansible-collection`. It has the ability to use `tox` to generate
content in the collection directory, this before the collection get
build.

add generate-and-build-ansible-collection

---

zuul.d/projects.yaml

Add more test coverage to ansible.netcommon collection.

Add cisco.asa jobs to ansible.netcommon

---

zuul.d/projects.yaml

this adds coverage for multiple ansible versions
depends on: https://github.com/ansible/ansible-zuul-jobs/pull/615
depends on: ansible/ansible-runner#487

add new ansible-runner jobs

---

github/projects.yaml
zuul.d/projects.yaml

`vmware_rest` default branch is now `main`.

vmware_rest default branch is now main

---

zuul.d/projects.yaml

The template is called `ansible-collections-community-vmware-rest`.
Also, disable the `squash-merge`.

vmware-rest: use the new dedicated template

---

zuul.d/projects.yaml

This adds more test coverage to ansible.netcommon.

Add cisco.ios jobs to ansible.netcommon

---

zuul.d/jobs.yaml

This is to help ze04 upload logs to rackspace.

Bump post-timeout to 3600

---

zuul.d/projects.yaml

Today this is used by network collections, a follow up commit will
rename that to network-integrated-queue.  We can then create
cloud-integrated-queue.

Remove cloud.common from integrated-queue

---

playbooks/ansible-changelog-fragment/run.yaml
zuul.d/jobs.yaml

We'll use this job to validate ansible pull-requests have the required
changelog fragments.

Add ansible-changelog-fragment job

---

playbooks/ansible-changelog-fragment/run.yaml

This should be the correct path to source code now.

Fix executor source path for ansible-changelog-fragment

---

playbooks/ansible-changelog-fragment/run.yaml

This should be a little better when checking if a new fragment has been
added.

Rework ansible-changelog-fragment playbook

---

zuul.d/jobs.yaml

If we change plugins / tests, we always want a changelog fragment.

Flip to job.files for ansible-changelog-fragment

---

zuul.d/projects.yaml

These projects are switched to use Github Actions instead of Zuul for their CI.
Related: https://github.com/ansible-community/molecule/pull/2811

Remove molecule projects from Zuul CI

---

zuul/tenants.yaml

Add `ansible-collections/vmware_rest_code_generator` in the tenants
list.

add vmware_rest_code_generator in tenants

---

github/projects.yaml
zuul/tenants.yaml

This is a partial revert, so we properly retire a project github.
This reverts commit 0b99be615d0a0ffa4cc9ccf73e72427194a8a299.

Revert "removed ansible-network.yang"

---

zuul.d/projects.yaml

This is the first step in retiring a project, we remove all jobs so we
can merge code without any testing.

Add noop jobs to ansible-network/yang repo

---

zuul.d/projects.yaml

Apply the publish-to-automation-hub template to cloud.common.

cloud.common: add publish-to-automation-hub

---

zuul.d/projects.yaml

This adds the first jobs to ansible.network collection.

Add ansible-collections/ansible.network jobs

---

zuul.d/projects.yaml

This reverts commit 83c286c37de7d14c6e1fb04fa05dab7f8cb995c1.

Revert "ansible-builder: Add ansible-tox-py36 jobs"

---

zuul.d/projects.yaml

Molecule vagrant does use github workflows as primary CI and we do not need:
* github-workflows job failure
* publish-to-pypi as we can publish using github directly

Drop templates from molecule-vagrant

---

zuul.d/projects.yaml

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/685
Associate the `ansible-collections-community-vmware-rest` template to the
`vmware.vmware_rest` repository.

vmwware_rest_code_generator: associate template

---

zuul.d/projects.yaml

Actually use:
`ansible-collections-community-vmware-rest-code-generator`
not:
`ansible-collections-community-vmware-rest`

vmware_rest_code_generator: use the right template

---

github/projects.yaml
zuul.d/projects.yaml
zuul/tenants.yaml

This github org has been deleted and was only to test github enterprise.

Remove EducationSwing/zuul-test from zuul

---

zuul.d/jobs.yaml

There was a breaking change a while again, this updates the value to
work again.

base-minimal-test: update ara_report_path value

---

zuul.d/projects.yaml

This will allow us to start building container images, with the goal of
testing them with ansible-builder.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/713

Add ansible-runner-container-image-jobs to ansible-runner

---

playbooks/buildset-registry/post.yaml
playbooks/buildset-registry/pre.yaml
playbooks/buildset-registry/run.yaml
zuul.d/jobs.yaml
zuul.d/secrets.yaml

This move ansible-buildset-registry into config-project so we can
publish images to our zuul-registry.

Add ansible-buildset-registry job

---

playbooks/buildset-registry/post.yaml

Now that we know zuul-registry is only, we can start to publish images
to it.

Use zuul-registry to store images

---

zuul/tenants.yaml

This allows us to run 3pci jobs for the project.

Add ansible/galaxy_ng to ansible tenant

---

zuul.d/jobs.yaml

This will allow other jobs to use to pull from the intermediate
registry.

Add ansible-buildset-registry-consumer job

---

zuul.d/projects.yaml

This project looks to have renamed to project-receptor/receptor and no
longer using zuul.

Remove project-receptor/python-receptor jobs

---

github/acls/ansible-network/aws_management.config

Fix syntax issue with aws_management.config

---

github/projects.yaml
zuul/tenants.yaml

The team has decided to create a new project, and not use zuul.

Remove project-receptor/python-receptor from zuul

---

zuul.d/projects.yaml

This allows us to do better cross-project testing between:
ansible-builder
ansible-runner
python-builder-image
python-base-image
All things needed to properly create an execution environment.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/735

Add projects to execution-environment shared queue

---

zuul.d/projects.yaml

We are moving to dynamic versioning with pbr

Remove usage of ansible-builder-projecttoml-and-setuppy-insync

---

playbooks/build-python-tarball/run.yaml
zuul.d/jobs.yaml

Some project use poetry, this is our first step to help automate their
releases for git tags.

Create release-ansible-python-poetry job

---

zuul.d/projects.yaml

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/738

Switch ansible/ansible-builder to use poetry release job

---

zuul.d/projects.yaml

This reverts commit c1ee4da3286edd320889ef5d0e4b6368a900a252.

Revert "Switch ansible/ansible-builder to use poetry release job"

---

zuul.d/projects.yaml

When ansible/ansible merges code to devel, build / publish our
ansible-core container image.

Add post jobs to ansible/ansible

---

zuul/tenants.yaml

Add the https://github.com/ansible/cloud-ee repository.
See: https://github.com/ansible/project-config/pull/705

tenants: add ansible/cloud-ee

---

zuul.d/projects.yaml

Now is the time to start moving to network-ee for all our testing.

Add network-ee jobs to arista.eos collection

---

zuul.d/projects.yaml

This allows us to properly test ansible/ansible changes for EEs.

Add ansible-runner-build-container-image-stable-2.9 to ansible/ansible

---

zuul.d/projects.yaml

When we merge stable-2.9 changes to ansible/ansible, also rebuild
ansible-runner.

Add ansible-runner container build job for ansible/ansible

---

playbooks/buildset-registry/pre.yaml

It is possible, that some jobs do not want to pull from the intermediate
registry, and only consume images from the buildset registry.

Allow jobs to toggle pulling from intermediate registry

---

playbooks/base-minimal-test/post-logs.yaml

They currently are updating their infra, and rather then hitting the
service (and failing) we can remove them for now.

Remove vexxhost for uploading logs

---

github/projects.yaml

This collection should only have a repo for now - it's still being developed by XLab and we don't want any Zuul checks/publishing until a later date.

Add new repo for servicenow.itsm

---

playbooks/ansible-core-ci/pre.yaml

There is some restriction in place that revent the use of the /tmp
directory.

ansible-core-ci: write the session fil in work_root

---

playbooks/ansible-core-ci/pre.yaml

Reverting because the file was actually generated on the controller
node. However, the template was generated from the executor. This was
actually the root cause of the problem.
This reverts commit a522f2d3d970b974046403e289b50274b74dfaa0.

Revert "ansible-core-ci: write the session fil in work_root"

---

zuul/tenants.yaml

ara is moving to GitHub for code review and would like to use Zuul for
testing pull requests.
I have wiped the existing Zuul config for the projects and set them to noop
to hopefully prevent issues.

Add ara projects to Zuul config

---

playbooks/refresh-automation-hub-token/run.yaml
zuul.d/jobs.yaml
zuul.d/projects.yaml
zuul.d/secrets.yaml

This both rotates our AH secret and creates a periodic job (1hr for now)
to refresh our token. This is sadly required, as tokens expire after 30
days of inactivity.  I think it is a poor design, especially given there
is no notification about the expire happening.

Create new job to refresh AH token

---

zuul.d/projects.yaml

Now that we know it is working, we can run every 24 hours.

Move refresh-automation-hub-token into periodic pipeline

---

playbooks/build-ansible-collection/run.yaml

We'll be removing tox from images soon, so ensure we have it installed
in jobs that use tox.

Ensure-tox is install for build-ansible-collection job

---

zuul.d/projects.yaml

Replace `publish-to-galaxy-3pci` by `publish-to-galaxy`. The collection
will be fully integrated.

c.aws: use publish-to-galaxy

---

zuul.d/projects.yaml

We're not supporting py27 anymore

remove py27 from network-runner jobs

---

github/projects.yaml

Not sure why, but acls didn't apply.

Add acl-config setting for ansible_content_collections_metrics

---

zuul/tenants.yaml

New community collection that exists since today (https://github.com/ansible-collections/community.dns).
CC @gundalow

Add community.dns as tenant

---

playbooks/ansible-changelog-fragment/run.yaml
roles/check_changelog_fragment/defaults/main.yml
roles/check_changelog_fragment/tasks/main.yml

Fixes #771 
The current `ansible-changelog-fragment` check leads to many false positives:
- When a new commit is added and is not squashed with the one adding the changelog fragment.
- When the pull-request contains a new plugin (module, filter, lookup...) and no changes of existing files.
This PR is a refactor of the whole check to look for add of a changelog fragment in the entire PR rather that just the last commit, and to not fail when a changelog fragment is not required.

look for add of a changelog fragment in the whole PR rather than the last commit

---

playbooks/ansible-changelog-fragment/run.yaml
playbooks/ansible-changelog-fragment/run_with_check_changelog_fragment.yaml
zuul.d/jobs.yaml

- `{{ zuul.project.default-branch }}` -> `{{ zuul.project['default-branch'] }}`
- use `playbooks/ansible-changelog-fragment/run_with_check_changelog_fragment.yaml`
to be able to test the role
- new job: ansible-changelog-fragment_2 (for testing)

mitigate PR 772 impact and add a fix

---

playbooks/ansible-changelog-fragment/run_with_check_changelog_fragment.yaml

Get the default branch using the Github API.

ansible-changelog-fragment: get the default branch

---

playbooks/base-minimal-test/pre.yaml

Zuul sets rsa key size as 3072, which causes failure in asa applaince.
This PR sets the rsa key size as 2048 for all appliances.

Set ssh key size as 2048 for rsa key

---

zuul.d/projects.yaml

Use the same configuration as molecule-vagrant, where zuul is only used as a 3rd party CI.

Reconfigure molecule-libvirt

---

zuul/tenants.yaml

The goal is to precache vmware/vsphere-automation-sdk-python.

tenant: add vmware/vsphere-automation-sdk-python

---

zuul.d/projects.yaml

Ansible 2.8 is EOL, lets stop testing.

Drop ansible 2.8 testing for ansible-runner

---

playbooks/ansible-collection/run-pre.yaml
playbooks/ansible-collection/run.yaml
playbooks/build-ansible-collection/run.yaml

This move to another tox entry point, to reduce the dependencies we pull
in.
Depends-On: https://github.com/ansible-network/releases/pull/17

Stop using venv for ansible-network/releases

---

zuul.d/projects.yaml

This reverts commit 9ad98ad22134beb605c43228cbb7972684efc8e2.
Bring back ansible-runner images when ansible/ansible merges code.

Partial Revert "remove ansible post jobs"

---

zuul.d/pipelines.yaml

With the upgrade to zuul 4.5.1, we likely no longer need to do this.

Remove status file from check pipeline

---

zuul.d/pipelines.yaml

Continue removing references to old checks api in our pipeline config.

Remove status from gate pipeline

---

playbooks/base-minimal-test/post-logs.yaml
zuul.d/jobs.yaml

We can now leverage zuul-web for this logic.

Stop publishing ara-report / htmlify logs

---

zuul.d/pipelines.yaml

In an effort to save some testing capacity, and allow for faster
merging.  Remove the need for testing to first pass check, to get into
gate.
This means, we could have more gate resets due to poor code. However, if
that happens we can always revert this.

Remove clean check requirement

---

zuul.d/pipelines.yaml

Now that we superceed check, we should allow for this to happen.

Allow recheck to trigger gate pipeline

---

zuul.d/pipelines.yaml

This is no longer needed since we removed the clean check requirement.

Remove check_run trigger for gate pipeline

---

zuul.d/pipelines.yaml

This is no longer needed and done by default now.

Remove mysql reporter from pipelines

---

zuul/tenants.yaml

We are adding this back to confirm zuul works properly.

Add back pabelanger/pabelanger-sandbox1 for 3pci

---

github/projects.yaml
zuul.d/projects.yaml
zuul/tenants.yaml

This project has moved to github access, we also no longer have admin
access on it to properly configure it for zuul. This fixes our promote
job.

Remove ansible/awx-ee project

---

zuul.d/pipelines.yaml

Lets see if we can move the LGTM logic to the gate pipeline, and not
race before the merge request.

Promote LGTM logic to gate pipeline

---

zuul.d/pipelines.yaml

This reverts commit e90903ad203929868fa42c10f80e1863ca4ac0c5.

Revert "Promote LGTM logic to gate pipeline"

---

zuul.d/pipelines.yaml

We added this event to the wrong pipeline.

Doh, fix bug with previous commit

---

zuul.d/pipelines.yaml

We don't need to report back to the checks API for this pipeline.

Simplify the lgtm pipeline

---

zuul.d/pipelines.yaml

When we dequeue jobs to move them into gate (superceed) we don't want a
red error.

Move check pipeline to skipped

---

zuul.d/projects.yaml

This will users to git tag a release for ansible.windows and collections
to be publish to galaxy / AH.

Add galaxy / AH publish jobs to ansible-collections/ansible.windows

---

zuul.d/pipelines.yaml

This deals with the issue where gate gets applied, but for whatever
reason lgtm isn't triggered properly.  This shouldn't happen often, but
adding this should be pretty safe.

Also run lgtm jobs on recheck

---

zuul.d/projects.yaml

`ansible-runner` is defining the py38 job in its repo and no longer needs py36 and py37 jobs.
Depends-On: https://github.com/ansible/ansible-runner/pull/768

Remove ansible-python3-jobs template from ansible-runner project

---

zuul.d/pipelines.yaml

This is an experiment to confirm semaphores are help based on pipeline
config order.

Reorder gate to see if sempahore works better

---

zuul.d/pipelines.yaml

This should stop failed check pipeline from being enqueued into gate.

Actually require ansible/check status for gate pipeline

---

zuul.d/pipelines.yaml

This will allow a user to re-run a failed check_run.

Allow re-run of failure check jobs

---

zuul.d/pipelines.yaml

The glob in `check aws?complete` is intentional. I think it's reasonable to accept common typos like `aws-complete`, `aws_complete`, and `aws complete`.

Add new pipeline to run aws complete ci in

---

github/projects.yaml
zuul.d/projects.yaml

Depends-On: https://github.com/ansible/project-config/pull/931
These repositories are now using `main` as their default branch. This
commit adjust Zuul's configuration.
Closes: https://github.com/ansible/project-config/issues/929

adjust the default-branch of some repositories

---

zuul.d/jobs.yaml

This should stop this job from running on AWS, which is where we are
seeing failures.

Upgrade to ubuntu-bionic-2vcpu for buildset-registry

---

zuul.d/projects.yaml

We are moving these jobs in-repo for better control over them.
Required-By: https://github.com/ansible/ansible-zuul-jobs/pull/1100

Remove ansible-navigator-jobs

---

github/projects.yaml
zuul.d/projects.yaml

This collection got moved under the openshift org. I'm not sure if there is something else that needs to be done to turn this on for the collection. I believe zuul should have the permissions it needs on that repo.

Enable community.okd at the new repo location

---

zuul.d/pipelines.yaml

Add a comment to explain third-party-check pipeline is
deprecated in favor of 3pci-check.

explain third-party-check is deprecated

---

zuul.d/projects.yaml

redhat.openshift is based on community.okd, but it's a manual process.
See: https://github.com/ansible/ansible-zuul-jobs/pull/1121#issuecomment-924131723

do not publish community.okd on AH

---

zuul.d/projects.yaml

We'd like to use python 3.8 in the `ansible-runner` linters job, so we are moving this job in repo. See https://github.com/ansible/ansible-runner/pull/859

Moving runner linter job to runner repo

---

playbooks/base-minimal-test/pre.yaml
playbooks/base-minimal/pre.yaml

Ensure our ec2 have got git installed before we continue to
prepare-workspace-git.
Git is pulled by cloud-init in the background and this leads
sometime to race condition.

enable the ec2/git workaround

---

zuul.d/projects.yaml

Reverting follow up to a quick discussion with Paul. To do that
properly, we should create a new ee-community template. We should also
add the collections to awx-ee.
This reverts commit de1e156a4096a486b1a19dfa9e5dae1edea65cbd.

Revert "ee-tests template for c.vmware and c.aws"

---

zuul.d/projects.yaml

Tried adding this setting to `ansible-runner` and `ansible-builder` repo project definitions (https://github.com/ansible/ansible-runner/pull/890 and https://github.com/ansible/ansible-builder/pull/296), but doesn't look like its working from there.

Switch runner and builder merge mode to squash-merge

---

playbooks/configure-tox-with-gh-cli/pre.yaml

zuul_work_dir used to deliver github token

tox linters with gh cli - update test directory

---

zuul.d/projects.yaml

Ensure tox linters validate projects default branch using ``gh`` cli

tox linters with gh cli

---

zuul.d/jobs.yaml

Turn project-config-tox-linters non-voting until we've got it stabilize
and we've generated the final token.

turn project-config-tox-linters non-voting

---

zuul.d/jobs.yaml

project-config linters job was temporary set as non voting before getting the permanent github token.
As this is integrate now via #980 this one can be merged after

revert non-voting job setting

---

zuul.d/projects.yaml

As we have removed all the network periodic jobs from ansible/ansible, the template ansible-test-network-integration is no longer needed.

Remove ansible-test-network-integration template from ansible/ansible

---

zuul/tenants.yaml

The nodepool configuration is specific to zuul.ansible.com. We will move
it in this directory. This way, we can reuse the rest of the repository
with SF.

ansible-zuul-jobs: load config from zuul.ansible.d/ too

---

zuul.d/jobs.yaml

We want to stop using centos-8-1vcpu nodeset, given it runs
on older flavors (which are slower then centos-8-stream).

Switch a few more jobs to centos-8-stream

---

zuul.d/projects.yaml

Ensure the vmware.vmware_rest is still defined and that we set
the right default branch.
This to avoid the following error:
x build-ansible-collection ERROR Project github.com/ansible-collections/vmware.vmware_rest does not have the default branch master in 19s

vmware.vmware_rest is a dep of network-ee-container-image-jobs

---

zuul.d/projects.yaml

`ansible-runner` is moving to using GHA for its CI (https://github.com/ansible/ansible-runner/pull/944) and will not be using Zuul at all going forward.

Remove ansible-runner project

---

zuul.d/projects.yaml

Reverts ansible/project-config#1003
ansible-runner project is needed for the network platform jobs. So reverting this change.

Revert "Remove ansible-runner project"

---

zuul.d/projects.yaml

All zuul jobs for `ansible-runner` are now handled at the repo level. Removing these jobs that have been replaced within the runner repo.

Update ansible-runner jobs

---

zuul.d/projects.yaml

ansible-runner does not use Zuul anymore. The jobs are not defined
anymore.
See: https://github.com/ansible/ansible-runner/pull/970

ansible/ansible: remove the runner jobs

---

zuul.d/projects.yaml

These collections now use SoftwareFactory to run the
publish-to-galaxy-3pci jobs.

community.*: disable publish-to-galaxy-3pci

---

zuul.d/projects.yaml

See: https://github.com/ansible/zuul-config/commit/d8cfe95eeb51eda3386039fc26f762374e803d83
Note that community.asa and community.yang don't use the 3pci template so I've left them as-is for now.

Community collections are published from a new Zuul

---

zuul.d/projects.yaml

See: https://github.com/ansible/zuul-config/pull/282

frr.frr is on SF now

---

zuul.d/projects.yaml

See: https://github.com/ansible/zuul-config/pull/346

cisco.iosxr is fully migrated
